### ISSUE TITLE
windows 快速建构包没内容

### ISSUE THREAD

**Issue by awewu** [yangjian102621/chatgpt-plus#10]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

![image](https://github.com/yangjian102621/chatgpt-plus/assets/57051851/ff5df6d5-b5e9-46e5-9f22-2458ccde2c49)
打开windows的快速建构包进入 localhost:5678 就是这样

### 重现步骤 🕹

一直都是这样

### 你的应用配置信息

自动生成的配置

**Comment by yangjian102621** [comment]
你这个是不是浏览器有什么特殊设置，都没有访问到 index.html, 你手动输入 html 地址试下 http://localhost:5678/chat/index.html

**Comment by awewu** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/57051851/c4c348c2-0bc0-460e-a594-14976b32b48b)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/57051851/0967a964-e496-42bc-b052-6e3b631f8e46)
都不行，chrome和edge两个浏览器都试过，不行

**Comment by yangjian102621** [comment]
你试下运行本地源码版本，或者在本机编译一下。这种情况感觉很奇怪，没有解析 html。

**Comment by awewu** [comment]
源码使用没问题，确实挺奇怪的
