### ISSUE TITLE
意见反馈的二维码替换功能

### ISSUE THREAD

**Issue by TimLiuDream** [yangjian102621/chatgpt-plus#100]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

功能反馈的二维码只能展示作者的，但是不能配置。。

### 示例 🌈

在管理后台可以配置对应的二维码。

**Comment by yangjian102621** [comment]
收到反馈，预计下个版本加上此功能。

**Comment by yangjian102621** [comment]
该功能已经在 v3.2.6 版本上线了
