### ISSUE TITLE
服务搭建完 不能注册

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/chatgpt-plus#101]
### ⚠️  确认 issue 是否已存在 ⚠️

- [x] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

linux centor os 7

### Bug 描述 📝

服务一键搭建好，登录8080/chat 需要注册，但注册时会报错
<img width="409" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/53415039-da81-4b7b-8b19-6263b3171ec8">

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
邮箱注册和手机号注册为了防止薅羊毛增加了短信验证码，如果需要可以在管理后台将邮件注册和手机号注册功能关闭，这样用户输入任意用户名都可以注册了。

**Comment by SericWong** [comment]
想要保留这个功能，现在问题是图显示不出来

**Comment by yangjian102621** [comment]
> 想要保留这个功能，现在问题是图显示不出来

想要保留这个功能就要去购买验证码服务的 token，没有 token 服务没法正常运行。

**Comment by geekqingxin** [comment]
并没有说明具体是哪个验证码服务的token,比如说应该配置哪一个?

**Comment by yangjian102621** [comment]
@geekqingxin https://www.bilibili.com/video/BV1Cc411t7CX/ 看下这个视频教程
