### ISSUE TITLE
Dalle3调用失败

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/chatgpt-plus#105]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

<img width="818" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/3c81133f-9cbb-4375-934e-0c282eb6c6ea">
用gpt3.5让画图，会报error with parse auth token: token signature is invalid: signature is invalid，管理后台配置了写作和绘画两个apikey，还是报这个问题

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
@SericWong README 文档中有 B 站上视频教程，你去看下。
