### ISSUE TITLE
发邮件有个bug，title字符集没改

### ISSUE THREAD

**Issue by wobushitiegan** [yangjian102621/chatgpt-plus#109]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

MacOS

### Bug 描述 📝

发邮件有个bug，title字符集没改

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
收到，这个是 API KEY 网站的问题，不属于此项目的 Bug。
