### ISSUE TITLE
任务推送失败: MidJourney 池子中没有没有可用的服务!

### ISSUE THREAD

**Issue by 810434666** [yangjian102621/chatgpt-plus#111]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

![微信图片_20240117192705](https://github.com/yangjian102621/chatgpt-plus/assets/101308088/3310c886-a317-4689-a768-c99a5ff716c6)
配置好后重启了还是不行，想问下这个是哪里出了问题

### 你的应用配置信息

![微信图片_20240117193031](https://github.com/yangjian102621/chatgpt-plus/assets/101308088/41f81ea7-5019-47f7-b777-15e45f3f83b1)

**Comment by yangjian102621** [comment]
mj-plus 要3.2.5 版本才支持，请使用 3.2.5 版本的镜像或者一键部署脚本。https://ai.r9it.com/docs/install/
