### ISSUE TITLE
支付订单出错

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/chatgpt-plus#113]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

linux

### Bug 描述 📝

<img width="715" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/e4112f5c-6172-4308-b850-a59ea229543e">
接入虎皮椒后，在会员页面，页面点支付会报这个问题
拉最新的代码，自己build（没有修改代码，只biuld 后端api代码），会出这个问题，如果直接docker拉镜像就不会报错

看到log内容：
Error 1054 (42S22): Unknown column 'username' in 'field list'
INSERT INTO `chatgpt_orders` (`created_at`,`updated_at`,`user_id`,`product_id`,`username`,`order_no`,`subject`,`amount`,`status`,`remark`,`pay_time`,`pay_way`,`deleted_at`)

我看了下3.2.4的chatgpt_orders，确实没有username，这个是代码版本和数据库版本不一致吗？但是用docker镜像的3.2.4版本就没这个问题，应该不是数据库字段错了，是现在这个代码版本有问题吗？
——————————————————————————————
现在这个版本的代码这里应该是有问题的？Username改成Mobile？并且把order.go的username也改成mobile 就可以了，这个是下个版本做了什么变化吗？不兼容现在的版本导致的？
	order := model.Order{
		UserId:    user.Id,
		Username:  user.Username,
		ProductId: product.Id,
		OrderNo:   orderNo,
		Subject:   product.Name,
		Amount:    product.Price - product.Discount,
		Status:    types.OrderNotPaid,
		PayWay:    payWay,
		Remark:    utils.JsonEncode(remark),
	}

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
数据库有更新，你需要执行下面的语句：
```sql
ALTER TABLE `chatgpt_orders` CHANGE `mobile` `username` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户明';
```
