### ISSUE TITLE
SD任务推送失败

### ISSUE THREAD

**Issue by woofei** [yangjian102621/chatgpt-plus#116]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

v3.2.6
SD采用秋葉一键运行的包，res/text2img.json也获取了消息复制替换。修改好的 text2img.json 映射到 docker 容器中去.
任务推送失败：error with save job: Error 1054 (42S22): Unknown column 'publish' in 'field list'

### 重现步骤 🕹

text2img.json格式如下：
{
  "fn_index": 104,
  "data": [
    "task(26h5vz3zdd8y7fj)",
    "a cute dog",
    "",
    [],
    20,
    "Euler a",
    false,
    false,
    1,
    1,
    7,
    -1,
    -1,
    0,
    0,
    0,
    false,
    512,
    512,
    false,
    0.7,
    2,
    "Latent",
    0,
    0,
    0,
    [],
    "None",
    false,
    false,
    "positive",
    "comma",
    0,
    false,
    false,
    "",
    "Seed",
    "",
    "Nothing",
    "",
    "Nothing",
    "",
    true,
    false,
    false,
    false,
    0,
    null,
    null,
    false,
    null,
    null,
    false,
    null,
    null,
    false,
    50,
    [],
    "",
    "",
    ""
  ],
  "session_hash": "5pij8h7xh27"
}

### 你的应用配置信息

```toml
[[SdConfigs]]
  Enabled = true
  ApiURL = "http://192.168.128.182:7860/?__theme=dark"
  ApiKey = ""
  Txt2ImgJsonPath = "res/sd/text2img.json"
```
  # 后端 API 程序
  chatgpt-plus-api:
    image: registry.cn-shenzhen.aliyuncs.com/geekmaster/chatgpt-plus-api:v3.2.6-amd64
    container_name: chatgpt-plus-api
    restart: always
    depends_on:
      - chatgpt-plus-mysql
      - chatgpt-plus-redis
    environment:
      - DEBUG=false
      - LOG_LEVEL=info
      - CONFIG_FILE=config.toml
    ports:

    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./conf/config.toml:/var/www/app/config.toml
      - ./logs:/var/www/app/logs
      - ./static:/var/www/app/static
      - ./res/sd:/var/www/app/res/sd

**Comment by yangjian102621** [comment]
数据库没有更新，缺少字段。执行下面的 SQL 语句。

```sql
ALTER TABLE `chatgpt_sd_jobs` ADD `publish` TINYINT(1) NOT NULL COMMENT '是否发布' AFTER `progress`;
```
