### ISSUE TITLE
管理界面操作用户存在的两个问题

### ISSUE THREAD

**Issue by chj9** [yangjian102621/chatgpt-plus#117]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

新增用户的时候，保存完，显示的过期日期不对，需要刷新才显示正确的
![image](https://github.com/yangjian102621/chatgpt-plus/assets/16426260/30ea7913-58dc-4a22-a987-8d44090327d3)
重置密码的时候账户为空
![image](https://github.com/yangjian102621/chatgpt-plus/assets/16426260/d62e0deb-5cbb-4fc3-bd8f-6cf63f25c78e)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
@chj9 收到，感谢反馈，已修复，将在在 v3.2.7 版本更新。
