### ISSUE TITLE
聊天界面特殊字符显示不出

### ISSUE THREAD

**Issue by chj9** [yangjian102621/chatgpt-plus#119]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

如图所示
![image](https://github.com/yangjian102621/chatgpt-plus/assets/16426260/727601ea-7a2b-4a57-8490-a273fa6f0519)

### 重现步骤 🕹

如图所示

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
如果是代码的话，你需要用 "``" 包裹，否则会自动被解析成 HTML 标签
