### ISSUE TITLE
希望提供编译好的arm64的Dokcer镜像

### ISSUE THREAD

**Issue by NEPDream** [yangjian102621/chatgpt-plus#121]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

目前在阿里云编译好的官方镜像中，添加-arm64后缀，显示镜像不存在，希望可以提供编译好的arm64的镜像文件。希望官方提供编译好的arm64镜像，而不是自己编译是因为，参考 #120 ，在官方的仓库中会存在tag下内容错配的问题，那自己编译arm64镜像时候，也可能因为仓库中tag下内容错配的问题，导致api目录下的/bin/chatgpt-plus-linux内容和当前tag版本是错的，这样自己编译出来的arm64镜像肯定就和数据库不匹配了。所以希望官方能够增加编译好的arm64镜像。避免自己编译可能产生的问题。
![image](https://github.com/yangjian102621/chatgpt-plus/assets/31023128/65d40617-d2de-4ff8-844e-8f79fe67ee0a)

### 示例 🌈

![image](https://github.com/yangjian102621/chatgpt-plus/assets/31023128/cd0ffac7-6830-4987-a7e4-207f0adc093e)

### 动机 🔦

未来arm架构的vps只会越来越多，是大势所趋，因为arm架构的vps拥有更强的性能，和更便宜的价格

**Comment by yangjian102621** [comment]
收到，感谢反馈，后续版本会提供 arm 架构版本
