### ISSUE TITLE
GPTs配置后，记录无法保存

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/chatgpt-plus#122]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

使用学长提供的GPTs示例配置gpt-4-gizmo-g-tc0eHXdgb
![image](https://github.com/yangjian102621/chatgpt-plus/assets/5850668/5a2bf429-149c-4d18-aa81-cb8716a81041)
在聊天页面切换其他tab，在回来聊天记录无法保存（其他GPTs暂时没发现，这个可能输出有特殊字符？）

log报错：failed to save reply history message: Error 3988 (HY000): Conversion from collation utf8mb3_general_ci into utf8mb4_0900_ai_ci impossible for parameter

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
这是因为你的数据不支持 utf8mb4 编码，而返回的信息中含有 unicode emoj 字符，所以没法保存。确保你的 MySQL 版本在 8.0 以上，且数据库的字符集是 utf8mb4。

**Comment by SericWong** [comment]
> 这是因为你的数据不支持 utf8mb4 编码，而返回的信息中含有 unicode emoj 字符，所以没法保存。确保你的 MySQL 版本在 8.0 以上，且数据库的字符集是 utf8mb4。

复现了下，确实emoji表情都无法存储，这个学长那不是必现吗？数据库我用的是8.0，编码也是utf8mb4，都是用的你的一键部署，看问题应该是写入的内容是utf8mb3_general_ci，问题在代码的写入侧？

**Comment by SericWong** [comment]
解决了，配置里默认是utf8，改成utf8mb4就好了。哈哈哈哈
