### ISSUE TITLE
开启众筹时，transid解析为空

### ISSUE THREAD

**Issue by 807660937** [yangjian102621/chatgpt-plus#123]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

能解析到金额，但transid为空
<img width="1329" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/23006385/2c97b3ab-e81a-4c85-82e9-4517fc9566a5">

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
请更新到最新版 v3.2.6

**Comment by 807660937** [comment]
<img width="241" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/23006385/5867141d-491e-41b2-9cab-b342046097c8">
但是最新的代码才到3.2.4呢
