### ISSUE TITLE
邮箱账号无法创建支付订单

### ISSUE THREAD

**Issue by 602753090** [yangjian102621/chatgpt-plus#125]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

邮箱账号在充值时，点击支付宝按钮弹出错误消息：生成支付订单失败：error with create order: Error
1406 (22001): Data too long for column 'mobile' at row 1
![IMG_2193](https://github.com/yangjian102621/chatgpt-plus/assets/46047354/33d34e94-5838-486e-9d7d-71815a169f81)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
你这是数据库没有更新，缺少字段。执行下面的 SQL 语句可以解决。
```sql
ALTER TABLE `chatgpt_orders` CHANGE `mobile` `username` VARCHAR(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户明';
```
