### ISSUE TITLE
GPT4搜索结果展示BUG

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/chatgpt-plus#127]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-4

### 操作系统

Linux

### Bug 描述 📝

<img width="458" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/6efd3c83-87cb-43f1-ab28-d7ac7e1bb737">
学长给的实例这里，搜索结果没展示URL，正常应该是会展示搜索到哪些链接内容的，应该是展示解析出的错？

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
URL 在下面。我这边是按照 API 返回原样展示的，解析没有出错，控制台打印出来的元数据就是这样。

![image](https://github.com/yangjian102621/chatgpt-plus/assets/4746061/37830fc2-04f1-4445-892f-1fe8c6af5811)
