### ISSUE TITLE
加载系统配置失败

### ISSUE THREAD

**Issue by 383766159** [yangjian102621/chatgpt-plus#128]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

安装完成后 打开管理面板就提示加载系统配置失败，具体图片如下
![image](https://github.com/yangjian102621/chatgpt-plus/assets/107017679/434e5ab5-b7fe-42c6-9bf7-91e853631de1)
然后登录前端也会提示加载失败，然后就进不去

### 重现步骤 🕹

打开管理面板，管理面板系统设置标签页和登陆的时候出现。

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by 383766159** [comment]
api的日志 	/go/chatgpt-plus/api/store/mysql.go:22:
dial tcp 192.168.16.2:3306: connect: connection refused
[Fx] ERROR		Failed to start: could not build arguments for function "main".main.func7
	/go/chatgpt-plus/api/main.go:150:
failed to build *wx.Bot:
could not build arguments for function "chatplus/service/wx".NewWeChatBot
	/go/chatgpt-plus/api/service/wx/bot.go:22:
failed to build *gorm.DB:
received non-nil error from function "chatplus/store".NewMysql
	/go/chatgpt-plus/api/store/mysql.go:22:
dial tcp 192.168.16.2:3306: connect: connection refused
2024/01/30 22:41:34 could not build arguments for function "main".main.func7 (/go/chatgpt-plus/api/main.go:150): failed to build *wx.Bot: could not build arguments for function "chatplus/service/wx".NewWeChatBot (/go/chatgpt-plus/api/service/wx/bot.go:22): failed to build *gorm.DB: received non-nil error from function "chatplus/store".NewMysql (/go/chatgpt-plus/api/store/mysql.go:22): dial tcp 192.168.16.2:3306: connect: connection refused
2024-01-30T22:41:35.638+0800	INFO	api/main.go:61	Loading config file: config.toml
[Fx] PROVIDE	*types.AppConfig <= main.main.func2()
[Fx] PROVIDE	*core.AppServer <= chatplus/core.NewServer()
[Fx] PROVIDE	*gorm.Config <= chatplus/store.NewGormConfig()
[Fx] PROVIDE	*gorm.DB <= chatplus/store.NewMysql()
[Fx] PROVIDE	*redis.Client <= chatplus/store.NewRedisClient()
[Fx] PROVIDE	embed.FS <= main.main.func4()
[Fx] PROVIDE	*xdb.Searcher <= main.main.func5()
[Fx] PROVIDE	*handler.ChatRoleHandler <= chatplus/handler.NewChatRoleHandler()
[Fx] PROVIDE	*handler.UserHandler <= chatplus/handler.NewUserHandler()
[Fx] PROVIDE	*chatimpl.ChatHandler <= chatplus/handler/chatimpl.NewChatHandler()
[Fx] PROVIDE	*handler.UploadHandler <= chatplus/handler.NewUploadHandler()
[Fx] PROVIDE	*handler.SmsHandler <= chatplus/handler.NewSmsHandler()
[Fx] PROVIDE	*handler.RewardHandler <= chatplus/handler.NewRewardHandler()
[Fx] PROVIDE	*handler.CaptchaHandler <= chatplus/handler.NewCaptchaHandler()
[Fx] PROVIDE	*handler.MidJourneyHandler <= chatplus/handler.NewMidJourneyHandler()
[Fx] PROVIDE	*handler.ChatModelHandler <= chatplus/handler.NewChatModelHandler()
[Fx] PROVIDE	*handler.SdJobHandler <= chatplus/handler.NewSdJobHandler()
[Fx] PROVIDE	*handler.PaymentHandler <= chatplus/handler.NewPaymentHandler()
[Fx] PROVIDE	*handler.OrderHandler <= chatplus/handler.NewOrderHandler()
[Fx] PROVIDE	*handler.ProductHandler <= chatplus/handler.NewProductHandler()
[Fx] PROVIDE	*admin.ConfigHandler <= chatplus/handler/admin.NewConfigHandler()
[Fx] PROVIDE	*admin.ManagerHandler <= chatplus/handler/admin.NewAdminHandler()
[Fx] PROVIDE	*admin.ApiKeyHandler <= chatplus/handler/admin.NewApiKeyHandler()
[Fx] PROVIDE	*admin.UserHandler <= chatplus/handler/admin.NewUserHandler()
[Fx] PROVIDE	*admin.ChatRoleHandler <= chatplus/handler/admin.NewChatRoleHandler()
[Fx] PROVIDE	*admin.RewardHandler <= chatplus/handler/admin.NewRewardHandler()
[Fx] PROVIDE	*admin.DashboardHandler <= chatplus/handler/admin.NewDashboardHandler()
[Fx] PROVIDE	*admin.ChatModelHandler <= chatplus/handler/admin.NewChatModelHandler()
[Fx] PROVIDE	*admin.ProductHandler <= chatplus/handler/admin.NewProductHandler()
[Fx] PROVIDE	*admin.OrderHandler <= chatplus/handler/admin.NewOrderHandler()
[Fx] PROVIDE	*service.AliYunSmsService <= chatplus/service.NewAliYunSmsService()
[Fx] PROVIDE	*service.CaptchaService <= main.main.func6()
[Fx] PROVIDE	*oss.UploaderManager <= chatplus/service/oss.NewUploaderManager()
[Fx] PROVIDE	*mj.Service <= chatplus/service/mj.NewService()
[Fx] PROVIDE	*service.SmtpService <= chatplus/service.NewSmtpService()
[Fx] PROVIDE	*wx.Bot <= chatplus/service/wx.NewWeChatBot()
[Fx] PROVIDE	*mj.ServicePool <= chatplus/service/mj.NewServicePool()
[Fx] PROVIDE	*sd.ServicePool <= chatplus/service/sd.NewServicePool()
[Fx] PROVIDE	*payment.AlipayService <= chatplus/service/payment.NewAlipayService()
[Fx] PROVIDE	*payment.HuPiPayService <= chatplus/service/payment.NewHuPiPay()
[Fx] PROVIDE	*payment.PayJS <= chatplus/service/payment.NewPayJS()
[Fx] PROVIDE	*service.Snowflake <= chatplus/service.NewSnowflake()
[Fx] PROVIDE	*service.XXLJobExecutor <= chatplus/service.NewXXLJobExecutor()
[Fx] PROVIDE	*handler.InviteHandler <= chatplus/handler.NewInviteHandler()
[Fx] PROVIDE	*handler.PromptHandler <= chatplus/handler.NewPromptHandler()
[Fx] PROVIDE	*admin.FunctionHandler <= chatplus/handler/admin.NewFunctionHandler()
[Fx] PROVIDE	*handler.FunctionHandler <= chatplus/handler.NewFunctionHandler()
[Fx] PROVIDE	*handler.TestHandler <= chatplus/handler.NewTestHandler()
[Fx] PROVIDE	fx.Lifecycle <= go.uber.org/fx.New.func1()
[Fx] PROVIDE	fx.Shutdowner <= go.uber.org/fx.(*App).shutdowner-fm()
[Fx] PROVIDE	fx.DotGraph <= go.uber.org/fx.(*App).dotGraph-fm()
[Fx] INVOKE		main.main.func3()
[Fx] INVOKE		main.main.func7()
[Fx] INVOKE		main.main.func8()
[Fx] INVOKE		main.main.func9()
2024-01-30T22:41:35.651+0800	INFO	service/xxl_job_service.go:24	XXL-JOB service is disabled
[Fx] INVOKE		main.main.func10()
[Fx] INVOKE		main.main.func11()
[Fx] INVOKE		main.main.func12()
[Fx] INVOKE		main.main.func13()
[Fx] INVOKE		main.main.func14()
[Fx] INVOKE		main.main.func15()
[Fx] INVOKE		main.main.func16()
[Fx] INVOKE		main.main.func17()
[Fx] INVOKE		main.main.func18()
[Fx] INVOKE		main.main.func19()
[Fx] INVOKE		main.main.func20()
[Fx] INVOKE		main.main.func21()
[Fx] INVOKE		main.main.func22()
[Fx] INVOKE		main.main.func23()
[Fx] INVOKE		main.main.func24()
[Fx] INVOKE		main.main.func25()
[Fx] INVOKE		main.main.func26()
[Fx] INVOKE		main.main.func27()
[Fx] INVOKE		main.main.func28()
2024-01-30T22:41:35.753+0800	INFO	payment/alipay_service.go:23	Disabled Alipay service
[Fx] INVOKE		main.main.func29()
[Fx] INVOKE		main.main.func30()
[Fx] INVOKE		main.main.func31()
[Fx] INVOKE		main.main.func32()
[Fx] INVOKE		main.main.func33()
[Fx] INVOKE		main.main.func34()
[Fx] INVOKE		main.main.func35()
[Fx] INVOKE		main.main.func36()
[Fx] INVOKE		main.main.func37()
[Fx] INVOKE		main.main.func38()
2024-01-30T22:41:35.779+0800	INFO	core/app_server.go:92	http://0.0.0.0:5678

**Comment by yangjian102621** [comment]
应该是你更新了数据库，但是程序版本没有更新。你这个看起来是比较老的版本了，建议更新到最新的稳定版。

**Comment by 383766159** [comment]
> 应该是你更新了数据库，但是程序版本没有更新。你这个看起来是比较老的版本了，建议更新到最新的稳定版。

我还试了重装系统 都没用

**Comment by yangjian102621** [comment]
最新版是 3.2.6
