### ISSUE TITLE
快速部署的怎么修改后台管理员密码呢

### ISSUE THREAD

**Issue by hbytw** [yangjian102621/chatgpt-plus#129]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 示例 🌈

![image](https://github.com/yangjian102621/chatgpt-plus/assets/43083918/add332c7-a578-4bdb-9507-3ffd5e3d1f62)

### 动机 🔦

快速部署的怎么修改后台管理员密码呢

**Comment by 383766159** [comment]
找到那个目录 比如chatgpt-plus文件夹内进入config文件夹修改config.toml 内有修改密码的地方
![image](https://github.com/yangjian102621/chatgpt-plus/assets/107017679/b07fa549-1237-4c29-b88f-30becfa766cd)
一般chatgpt-plus文件夹是在你当时运行一键部署的目录下

**Comment by hbytw** [comment]
直接是docker拉起来的，需要进容器修改，这个文件的路径是什么呢？

**Comment by hbytw** [comment]
找到了，谢谢，已经修改。

**Comment by 383766159** [comment]
我是用docker-compose拉起来的，他本地目录会生成一个，如果你要进容器的话docker ps，就在容器内的一开始目录就有
![image](https://github.com/yangjian102621/chatgpt-plus/assets/107017679/5d1cf651-e912-4fdf-853b-2ffa7ffffdea)
