### ISSUE TITLE
【建议】可以加入langchain功能吗 支撑上传下载文档，基于文档进行问答

### ISSUE THREAD

**Issue by nuass** [yangjian102621/chatgpt-plus#13]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

支撑上传文档，基于文档+llm进行问答，例如langchain

### 示例 🌈

langchain

### 动机 🔦

这样可以方便一些用户的问答，

**Comment by yangjian102621** [comment]
langchain 是 python 写的，不好直接继承，不过可以自己实现这个功能 ，本质上还是基于 embed 的向量搜索 + 指定学习样本问答实现。

**Comment by wshze** [comment]
@yangjian102621 功能建议：建议增加邮箱注册功能。另外众筹哪个功能在哪里换微信啊？谢谢

**Comment by yangjian102621** [comment]
微信收款码需要自己更换。在 public/images/reward.png 换成自己的就好了

**Comment by yangjian102621** [comment]
> @yangjian102621 功能建议：建议增加邮箱注册功能。另外众筹哪个功能在哪里换微信啊？谢谢

新版众筹功能支持只管理后台上传收款二维码了。

**Comment by yangjian102621** [comment]
> 模型可以根据用户开放吗？比如GPT4我只想给个别人用。另外还可以考虑增加违禁词（过滤）

目前还不可以。后续版本可能会考虑加上。违禁词过滤功能因为要调用第三方API，所以这个是付费功能。
