### ISSUE TITLE
Midjourney Plus画图或者用GPT3.5或者GPT4报令牌无效

### ISSUE THREAD

**Issue by luchenwei9266** [yangjian102621/chatgpt-plus#133]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

已多次确认key是没有问题的，Midjourney Plus的key我配置在```config.toml```中，OpenAI的key是我本身自己chatgpt的账号弄出来的key，但无论是画图还是对话，都是说令牌无效
![image](https://github.com/yangjian102621/chatgpt-plus/assets/9455826/a73287c6-5211-44ae-bb77-bc408a624e25)

### 你的应用配置信息

![image](https://github.com/yangjian102621/chatgpt-plus/assets/9455826/ced63f22-3c12-4fc3-9c55-a7c216e50593)

**Comment by yangjian102621** [comment]
API 地址配置的不对，应该是 https://api.chat-plus.net
