### ISSUE TITLE
mj的点击生成后，页面不更新

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/chatgpt-plus#135]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-4

### 操作系统

Linux

### Bug 描述 📝

<img width="598" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/796807a7-4b4f-4629-8b5c-80966e0ad46c">

在mac电脑上，Chrome和Safari，windows电脑chrome都可以稳定复现
连续多画几张 就出现这个问题了

① 点击生成图片，不显示『任务正在排队』
② 有时候『任务排队』出现，但不会更新进度条 
③ 出现了进度更新，但会卡到一定进度，不落到图片下载，在mj后台看 可以看到图片已经画完了，页面就是不刷新。
debug可以看到finishedJobs.value = jobs一般会更新，但图就是不刷新，问题应该就是在前端展示

刷新后可以页面会有变化。

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
已修复。
