### ISSUE TITLE
ERROR mj/service.go:79 绘画任务执行失败：error with http request: <nil><nil>表单主体无效

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/chatgpt-plus#136]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-4

### 操作系统

Linux

### Bug 描述 📝

<img width="509" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/56fbb98c-4b4d-4e08-85db-0883c2886ce8">

<img width="488" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/ef07c3f6-c3d8-4208-a9ad-89c720a73174">

操作过程：
对一个图，先执行V再执行U，就会出现这种错位，4张图合集下面不显示UV了，单图下面显示UV，如果对单图的UV点击，就会报错：ERROR mj/service.go:79 绘画任务执行失败：error with http request: <nil><nil>表单主体无效
应该是锁的问题？因为V的操作返回结果是慢的，U的操作返回结果很快，先点了V，但拿到的结果是先返回U的结果，所以组成了U+底下的操作？

### 重现步骤 🕹

对一张图先点V再点U（连续），这个问题必现

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
收到反馈，已经在 v3.2.7 修复这个 Bug。
