### ISSUE TITLE
有没有大佬出个宝塔教程

### ISSUE THREAD

**Issue by Rockney99** [yangjian102621/chatgpt-plus#14]

**Comment by yangjian102621** [comment]
我这边在搞 docker-compose 部署，这样就不需要宝塔了，直接用容器，一跳命令完成部署。

**Comment by Rockney99** [comment]
> 我这边在搞docker-compose部分，这样就不需要宝塔了，直接使用容器，一次跳命命令完成部分。

好的

**Comment by yangjian102621** [comment]
@Rockney99 参考 docker-compose 部署教程 https://github.com/yangjian102621/chatgpt-plus#docker-%E5%BF%AB%E9%80%9F%E9%83%A8%E7%BD%B2
