### ISSUE TITLE
后台角色管理不支持emoji

### ISSUE THREAD

**Issue by kaine380** [yangjian102621/chatgpt-plus#140]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

MacOS

### Bug 描述 📝

后台的角色管理不支持emoji [打招呼、上下文信息字段],初步判断是数据库默认排序规则的问题
![WX20240210-172812@2x](https://github.com/yangjian102621/chatgpt-plus/assets/101698605/d1170d48-e07d-43d2-916a-d5867dfdaa74)
![WX20240210-172829@2x](https://github.com/yangjian102621/chatgpt-plus/assets/101698605/145a08e4-fdde-4a3b-aae3-513e20256d52)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
这是你数据库编码的问题，你百度一下，mysql  如何存储 emoj 表情
