### ISSUE TITLE
对话里输入<xxx>内容，就会消失

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/chatgpt-plus#141]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

MacOS

### Bug 描述 📝

![2360d71f53a3f9fed43ae9f57c9f346f](https://github.com/yangjian102621/chatgpt-plus/assets/5850668/4e6210e0-4913-4fc6-9511-7d561a6f6270)

对话框输入\<xxx\>的内容，聊天内容就不展示，模型会返回对话

### 重现步骤 🕹

可以复现

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by kaine380** [comment]
我也发现了,尖括号的内容被视为标签而导致内容不被显示了

**Comment by yangjian102621** [comment]
已修复在 v3.2.7 版本。
