### ISSUE TITLE
iphone chrome 注册页无法正常验证

### ISSUE THREAD

**Issue by yuwine77** [yangjian102621/chatgpt-plus#144]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

iphone chrome 注册页无法正常验证
iphone11 pro max 点不上字
![Uploading 微信图片_20240218140431.jpg…]()

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
感谢反馈，以经在 v3.2.7 版本修复
