### ISSUE TITLE
上传文件后 无法删除 一直在页面显示

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/chatgpt-plus#145]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

MacOS

### Bug 描述 📝

<img width="484" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/cb11f68d-a8e4-4764-a740-a2fa51b36709">

1. 文件上传后 一直在这显示，会越来越多，无法删除，可以不需要在这里保存并显示文件的，每次从+传就好了

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
收到，此功能已经在 v3.2.7 实现。
![image](https://github.com/yangjian102621/chatgpt-plus/assets/4746061/e09548b2-3835-47c0-a06d-bc303ecf2be6)
