### ISSUE TITLE
非常严重的BUG！！！！！！ 获取任意用户的回话信息

### ISSUE THREAD

**Issue by MaZhaolin** [yangjian102621/chatgpt-plus#148]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

MacOS

### Bug 描述 📝

登陆之后能拿着自己登陆以后token获取所有人的对话信息，接口没做鉴权，换个用户id就能拿到会话token 拿会话token 可以获取别人记录 发送消息也可以 

### 重现步骤 🕹

直接拿着登录后的token 去请求会话列表，user_id换成任意数字就能获取别人的会话列表

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by 1162790110** [comment]
哇 居然是真的

**Comment by gotoworld** [comment]
<img width="522" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/8605471/7159211d-c847-40c7-a93a-963db6a53a64">

**Comment by gotoworld** [comment]
我这边没有重现出来，在3.2.6 （dev分支）的最新版本下没法重现

**Comment by MaZhaolin** [comment]
> Reference in new

我也是同样的版本，检查下header里面是否正确的设置了token，这是我直接在他的演示站测出来的
<img width="885" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/13713662/c9428454-4867-4af5-bbed-bd5a403148e8">

**Comment by kaine380** [comment]
是不是管理员的token

**Comment by yangjian102621** [comment]
已修复 4.0.0
