### ISSUE TITLE
是否可以更换API为api2d？

### ISSUE THREAD

**Issue by jiwei3187553** [yangjian102621/chatgpt-plus#15]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

chatgpt因为网络问题我们不够稳定，一直用的api2d,系统是否支持api2d的接口

**Comment by yangjian102621** [comment]
去管理后台更改配置

![image](https://github.com/yangjian102621/chatgpt-plus/assets/4746061/f72640e0-6d36-4cd4-8886-37510263bec1)
