### ISSUE TITLE
"更新数据库失败"

### ISSUE THREAD

**Issue by naizhao** [yangjian102621/chatgpt-plus#152]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

数据库写入操作失败，debug打开看不到任何错误log
```
 environment:
      - DEBUG=true
```
![CleanShot 2024-03-03 at 01 56 09@2x](https://github.com/yangjian102621/chatgpt-plus/assets/1012276/663b1c66-0432-48f3-a00a-c6ac5043cc50)
![CleanShot 2024-03-03 at 02 00 22@2x](https://github.com/yangjian102621/chatgpt-plus/assets/1012276/01927de9-3e00-4e9a-86d9-2ff952d0fb78)
![CleanShot 2024-03-03 at 02 01 11@2x](https://github.com/yangjian102621/chatgpt-plus/assets/1012276/eef19cae-6f29-4543-978a-b3819c034f52)

![CleanShot 2024-03-03 at 01 58 53@2x](https://github.com/yangjian102621/chatgpt-plus/assets/1012276/dd97e9be-cca0-430e-bc4f-135b5a922ce1)
![CleanShot 2024-03-03 at 01 59 03@2x](https://github.com/yangjian102621/chatgpt-plus/assets/1012276/85d0b4c6-f6af-4242-a4ac-bcf64beea86b)
![CleanShot 2024-03-03 at 01 59 18@2x](https://github.com/yangjian102621/chatgpt-plus/assets/1012276/ade2a857-7778-4a3d-af66-9175836fd40a)

### 重现步骤 🕹

正常docker compose安装

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by kokojacket** [comment]
+1 @yangjian102621

**Comment by yangjian102621** [comment]
应该是缺少字段吧，你确保你的数据库版本更新到 3.2.7

**Comment by kokojacket** [comment]
@yangjian102621 chatgpt-plus-api和chatgpt-plus-web:v3.2.7都是2.3.7，mysql容器是latest。

**Comment by yangjian102621** [comment]
收到，此 Bug 已经修复，近期会上线。
