### ISSUE TITLE
本地启动go run main.go时报错

### ISSUE THREAD

**Issue by bosen365** [yangjian102621/chatgpt-plus#153]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

MacOS

### Bug 描述 📝

# github.com/quic-go/quic-go/internal/qtls
../../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.35.1/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration

### 重现步骤 🕹

提示版本不兼容，无法启动成功

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yinnxinn** [comment]
go用的哪个版本呢

**Comment by yangjian102621** [comment]
@bosen365 看下编译环境的文档，https://ai.r9it.com/docs/dev/

**Comment by yinnxinn** [comment]
邮件已收到，谢谢
