### ISSUE TITLE
宝塔部署的前后端下载地址在哪里

### ISSUE THREAD

**Issue by 366me** [yangjian102621/chatgpt-plus#154]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

宝塔部署的前后端下载地址在哪里

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
不需要前后端，使用一键部署即可。
文档地址：https://ai.r9it.com/docs/install/baota.html
