### ISSUE TITLE
MJ画图报错

### ISSUE THREAD

**Issue by iceiccy** [yangjian102621/chatgpt-plus#155]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

我在配置完config.toml里的MJ设置后，画图提示：原因：请求 API 出错：json: cannot unmarshal string into Go struct field ErrRes.error of type struct { Message string "json:\"message\"" },

### 重现步骤 🕹

![微信截图_20240303201501](https://github.com/yangjian102621/chatgpt-plus/assets/52325430/60ae4348-b30c-454e-857b-1a26870f96ba)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```
Listen = "0.0.0.0:5678"
ProxyURL = "" # 如 http://127.0.0.1:7777
MysqlDns = "root:12345678@tcp(chatgpt-plus-mysql:3306)/chatgpt_plus?charset=utf8&parseTime=True&loc=Local"
StaticDir = "./static" # 静态资源的目录
StaticUrl = "/static" # 静态资源访问 URL
AesEncryptKey = ""
ImgCdnURL = ""
WeChatBot = false

[Session]
  SecretKey = "azyehq3ivunjhbntz78xtddysfucxakadq4qbfrt0b7q3lnvg80" # 注意：这个是 JWT Token 授权密钥，生产环境请务必更换
  MaxAge = 86400

[Manager]
  Username = ""
  Password = "" # 如果是生产环境的话，这里管理员的密码记得修改

[Redis] # redis 配置信息
  Host = "chatgpt-plus-redis"
  Port = 6379
  Password = "12345678"
  DB = 0

[ApiConfig] # 微博热搜，今日头条等函数服务 API 配置，此为第三方插件服务，如需使用请联系作者开通
  ApiURL = ""
  AppId = ""
  Token = ""

[SmsConfig] # 阿里云短信服务配置
  AccessKey = ""
  AccessSecret = ""
  Product = "Dysmsapi"
  Domain = "dysmsapi.aliyuncs.com"
  Sign = ""
  CodeTempId = ""

[SMS] # Sms 配置，用于发送短信
   Active = "Ali" # 当前启用的短信服务，默认使用阿里云
   [SMS.Bao]
      Username = ""
      Password = ""
      Domain = "api.smsbao.com"
      Sign = "【极客学长】"
      CodeTemplate = "您的验证码是{code}。5分钟有效，若非本人操作，请忽略本短信。"
   [SMS.Ali]
      AccessKey = ""
      AccessSecret = ""
      Product = "Dysmsapi"
      Domain = "dysmsapi.aliyuncs.com"
      Sign = ""
      CodeTempId = ""

[OSS] # OSS 配置，用于存储 MJ 绘画图片
   Active = "local" # 默认使用本地文件存储引擎
   [OSS.Local]
     BasePath = "./static/upload" # 本地文件上传根路径
     BaseURL = "/static/upload" # 本地上传文件根 URL 如果是线上，则直接设置为 /static/upload 即可
   [OSS.Minio]
     Endpoint = "" # 如 172.22.11.200:9000
     AccessKey = "" # 自己去 Minio 控制台去创建一个 Access Key
     AccessSecret = ""
     Bucket = "chatgpt-plus" # 替换为你自己创建的 Bucket，注意要给 Bucket 设置公开的读权限，否则会出现图片无法显示。
     UseSSL = false
     Domain = "" # 地址必须是能够通过公网访问的，否则会出现图片无法显示。
   [OSS.QiNiu] # 七牛云 OSS 配置
       Zone = "z2" # 区域，z0：华东，z1: 华北，na0：北美，as0：新加坡
       AccessKey = ""
       AccessSecret = ""
       Bucket = ""
       Domain = "" # OSS Bucket 所绑定的域名，如 https://img.r9it.com

[[MjConfigs]]
  Enabled = false
  UserToken = ""
  BotToken = ""
  GuildId = ""
  ChanelId = ""
  UseCDN = false #是否使用反向代理访问，设置为true下面的设置才会生效
  DiscordAPI = "" # discord API 反代地址
  DiscordCDN = "" # mj 图片反代地址
  DiscordGateway = "" # discord 机器人反代地址

[[MjPlusConfigs]]
  Enabled = true
  ApiURL = "https://api.openai-hk.com"
  CdnURL = "" # CND 加速的 URL，如果有的话就设置
  Mode = "turbo" # MJ 绘画模式，可选值 relax/fast/turbo
  ApiKey = "hk-5yfyn91000d74b770"
  NotifyURL = "https://a.vhang.com" # 这里需要改成你的域名

[[SdConfigs]]
  Enabled = false
  ApiURL = ""
  ApiKey = ""
  Txt2ImgJsonPath = "res/sd/text2img.json"

[XXLConfig] # xxl-job 配置，需要你部署 XXL-JOB 定时任务工具，用来定期清理未支付订单和清理过期 VIP，如果你没有启用支付服务，则该服务也无需启动
  Enabled = false # 是否启用 XXL JOB 服务
  ServerAddr = "http://172.22.11.47:8080/xxl-job-admin" # xxl-job-admin 管理地址
  ExecutorIp = "172.22.11.47" # 执行器 IP 地址
  ExecutorPort = "9999" # 执行器服务端口
  AccessToken = "xxl-job-api-token" # 执行器 API 通信 token
  RegistryKey = "chatgpt-plus" # 任务注册 key

[AlipayConfig]
  Enabled = false # 启用支付宝支付通道
  SandBox = false # 是否启用沙盒模式
  UserId = "2088721020750581" # 商户ID
  AppId = "9021000131658023" # App Id
  PrivateKey = "certs/alipay/privateKey.txt" # 应用私钥
  PublicKey = "certs/alipay/appPublicCert.crt" # 应用公钥证书
  AlipayPublicKey = "certs/alipay/alipayPublicCert.crt" # 支付宝公钥证书
  RootCert = "certs/alipay/alipayRootCert.crt" # 支付宝根证书
  NotifyURL = "https://ai.r9it.com/api/payment/alipay/notify" # 支付异步回调地址

[HuPiPayConfig]
  Enabled = false
  Name = "wechat"
  AppId = "201906161477"
  AppSecret = "7f403199d510fb2c6f0b9f2311800e7c"
  PayURL = "https://api.xunhupay.com/payment/do.html"
  NotifyURL = "https://ai.r9it.com/api/payment/hupipay/notify"

[SmtpConfig] # 注意，阿里云服务器禁用了25号端口，所以如果需要使用邮件功能，请别用阿里云服务器
  Host = "smtp.163.com"
  Port = 25
  AppName = "极客学长"
  From = "test@163.com" # 发件邮箱人地址
  Password = "" #邮箱 stmp 服务授权码

[JPayConfig] # PayJs 支付配置
  Enabled = false
  Name = "wechat" # 请不要改动
  AppId = "" # 商户 ID
  PrivateKey = "" # 秘钥
  ApiURL = "https://payjs.cn/api/native"
  NotifyURL = "https://ai.r9it.com/api/payment/payjs/notify" # 异步回调地址，域名改成你自己的

**Comment by yangjian102621** [comment]
```
[[MjPlusConfigs]]
Enabled = true
ApiURL = "https://api.openai-hk.com/"
CdnURL = "" # CND 加速的 URL，如果有的话就设置
Mode = "turbo" # MJ 绘画模式，可选值 relax/fast/turbo
ApiKey = "hk-5yfyn91000d74b770"
NotifyURL = "https://a.vhang.com/" # 这里需要改成你的域名
```
你这个配置是不对的，NotifyURL 要填写完整的地址，而不是域名，只是让你改域名，而不是让你把整个地址替换成域名。还有，确保你的这个这个中转 API 的地址是对的。并不是所有的中转 API 的参数和路径都是兼容的。

**Comment by lmq352489099** [comment]
> ```
> [[MjPlusConfigs]]
> Enabled = true
> ApiURL = "https://api.openai-hk.com/"
> CdnURL = "" # CND 加速的 URL，如果有的话就设置
> Mode = "turbo" # MJ 绘画模式，可选值 relax/fast/turbo
> ApiKey = "hk-5yfyn91000d74b770"
> NotifyURL = "https://a.vhang.com/" # 这里需要改成你的域名
> ```
> 
> 你这个配置是不对的，NotifyURL 要填写完整的地址，而不是域名，只是让你改域名，而不是让你把整个地址替换成域名。还有，确保你的这个这个中转 API 的地址是对的。并不是所有的中转 API 的参数和路径都是兼容的。

不用域名 用IP地址是可以的嘛
