### ISSUE TITLE
请问如何调用星火的绘图接口

### ISSUE THREAD

**Issue by Timoshao** [yangjian102621/chatgpt-plus#158]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

如何使用星火的绘图API
https://www.xfyun.cn/doc/spark/Web.html#_1-%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E

**Comment by yangjian102621** [comment]
星火的绘图接口不打算接入，需要的可以自行接入。
