### ISSUE TITLE
未来是否可以支持claude的文件传输

### ISSUE THREAD

**Issue by yys45623** [yangjian102621/chatgpt-plus#159]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

未来是否可以支持claude的文件传输

**Comment by yangjian102621** [comment]
Claude3 是多态模型，本身就支持识别文件和图片的。不需要做额外额支持，你只需要上传你的文件并选择文件地址放在对话框中就可以。
