### ISSUE TITLE
登录时后台时登录失败，Request failed with status code 502

### ISSUE THREAD

**Issue by longtiequan** [yangjian102621/chatgpt-plus#16]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

大佬你好，我是在虚拟机上用docker部署的，安装部署过程中没有报错，登录时报错了,前端移动端我都试过了，报同样的错误
![0d3033c221dae29f4d169f682c15cf2](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/5a0723ef-c2aa-415d-a0a1-d1d69271e7d9)

### 重现步骤 🕹

我是在虚拟机上用docker部署的，安装运行过程中都没有报错，登录后台时报错了

### 你的应用配置信息

Listen = "0.0.0.0:5678"
#ProxyURL = "http://172.22.11.200:7777"
ProxyURL = "http://127.0.0.1:7777"
MysqlDns = "root:12345678@tcp(172.28.173.76:3307)/chatgpt_plus?charset=utf8mb4&parseTime=True&loc=Local"
StaticDir = "./static"
StaticUrl = "http://localhost:8080/static"

[Session]
  Driver = "cookie"
  SecretKey = "8k0c67y2or1n7kbmn1w1c86ygqscguoktuf9t524jm64ls585z8uibpdssiy128s"
  Name = "CHAT_PLUS_SESSION"
  Path = "/"
  Domain = ""
  MaxAge = 86400
  Secure = false
  HttpOnly = false
  SameSite = 2

[Manager]
  Username = "admin"
  Password = "admin_1234"

[Redis]
  Host = "localhost"
  Port = 6379
  Password = ""

系统版本是centos 7，内核是3.10.0-1062.el7.x86_64，内存为8G，cpu为2核，硬盘容量128G

**Comment by yangjian102621** [comment]
502 的意思是后端 API 服务没有启动，或者你 nginx 转发IP 写错了。

**Comment by longtiequan** [comment]
大佬，我刚刚发现是我有一个IP没有改，现在改过来了，需要重启所有服务吗？重启的脚本是不是那个build.sh文件呢
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/6be53caf-f017-484c-b0c2-91374cad9d36)

**Comment by yangjian102621** [comment]
重启就是先停止，在启动。 docker-compose down, 然后再执行  docker-compose up -d

**Comment by longtiequan** [comment]
![5f00195656e8e2a820ef554b06ea090](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/791538a9-5579-498b-a7f4-deee5016127d)

那个命令我肯定知道。。试过了还是会报错502，这个是我没成功启动吗？

**Comment by longtiequan** [comment]
![d5e13636f235d33c9ed2cac360b8807](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/e6f4ae23-6b66-4c80-b031-33ba88a2159a)
![097e19fbb9a8896483c8faa55f14e9f](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/1923592f-56ab-4f3d-a347-cf5ff5fd6952)

这是chatgpt-plus.conf文件的配置，大佬能看看有问题吗？

**Comment by yangjian102621** [comment]
如果后端部署成功了还是提示 502， 那么就可能是你后端的容器暴露的端口没有开放，在防火墙上开一下 6789 这个端口。

**Comment by longtiequan** [comment]
我的防火墙是禁用的，大佬还有什么别的方向吗

**Comment by longtiequan** [comment]
解决这个问题了，需要修改MySQLDns的那个地址，改成自己服务器自己的地址

**Comment by number9902** [comment]
> 解决这个问题了，需要修改MySQLDns的那个地址，改成自己服务器自己的地址

请问在哪里修改MySQLDns
