### ISSUE TITLE
无法正常返回消息

### ISSUE THREAD

**Issue by Lichard-Lu** [yangjian102621/chatgpt-plus#160]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

![image](https://github.com/yangjian102621/chatgpt-plus/assets/64761101/2c7845f0-2e25-4553-9a76-2c0b69203cc3)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/64761101/a74d97c3-4c84-460e-8820-f7992e33b276)
使用其他的第三方api key, 在对话时无法正常返回消息，后端报错信息如上

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by hzw-object** [comment]
接口转发报错了,可以打印一下,接口返回报错信息,"<"这个感觉是404了

**Comment by Lichard-Lu** [comment]
感谢大佬，已解决，直接复制了第三方接口的url，需要在后面添加/v1/chat/completions
