### ISSUE TITLE
超长文本会触发 无限重复，log会打爆

### ISSUE THREAD

**Issue by SericWong** [yangjian102621/chatgpt-plus#161]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

<img width="1519" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/5850668/650889a8-bd9f-451e-9229-310095bbefc8">

输入超长文本会重复打印log，容易把日志打爆

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
收到反馈，此 Bug 将会在新版本中修复。
