### ISSUE TITLE
收款二维码不登录, 所有用户无法登陆.

### ISSUE THREAD

**Issue by VitoYane** [yangjian102621/chatgpt-plus#171]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

在这个文件tail -f logs/app.log登陆收款微信, 如果这个不登录, 所有用户都无法登陆, 包括后台管理员也不能登陆后台. 提示502

只要扫码登陆了这个微信就好了.

### 重现步骤 🕹

配置中打开wechatbot, 
然后登陆, 此时一切正常. 
重启所有容器
用户无法登陆, 后台无法登陆, 提示502

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
你配置了启动微信机器人，但是又不登录，意味着整个服务是启动失败的，必然导致访问所有的服务都是 502，因为你整个 API 后端服务就没有起来。

**Comment by VitoYane** [comment]
> 你配置了启动微信机器人，但是又不登录，意味着整个服务是启动失败的，必然导致访问所有的服务都是 502，因为你整个 API 后端服务就没有起来。

感觉这个耦合度有点高了, 我的理解是微信机器人只是负责众筹这块的业务, 不是每天都有众筹. 而向gpt提问是每天都会发生的. 用一个地频次业务影响高频次业务, 感觉有点问题.

当然, 目前这样也有好处, 保障资金通道一定是畅通的. 避免影响众筹的热情.

**Comment by yangjian102621** [comment]
> > 你配置了启动微信机器人，但是又不登录，意味着整个服务是启动失败的，必然导致访问所有的服务都是 502，因为你整个 API 后端服务就没有起来。
> 
> 感觉这个耦合度有点高了, 我的理解是微信机器人只是负责众筹这块的业务, 不是每天都有众筹. 而向gpt提问是每天都会发生的. 用一个地频次业务影响高频次业务, 感觉有点问题.
> 
> 当然, 目前这样也有好处, 保障资金通道一定是畅通的. 避免影响众筹的热情.

这不是耦合度的问题，是依赖的问题，关键服务没有启动成功，系统就不能正常提供服务，如果你要略过这些错误，到时候用户跟你反馈他转账了，但是没法核销，请问你该如何排查问题呢，如果你没有看过源码，这种问题你肯定一脸懵逼。
