### ISSUE TITLE
用户名的逻辑问题

### ISSUE THREAD

**Issue by VitoYane** [yangjian102621/chatgpt-plus#172]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

![image](https://github.com/yangjian102621/chatgpt-plus/assets/17432059/f3189f0d-6927-4a8a-9438-bc4f266148ff)
这两个开关关闭, 可以注册, 不需要手机或者邮件验证. 但是登陆的时候, 限制必须是手机号或者邮箱
![image](https://github.com/yangjian102621/chatgpt-plus/assets/17432059/b9506186-e700-4c12-ae8b-5d5fed9764ff)

### 重现步骤 🕹

1. 后台关闭邮箱和手机号勾选
2. 注册一个新用户取名test1
3. 注册成功后自动进入, 点击注销登陆
4. 使用test1登陆, 无法登陆

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
这个 Bug 已经在最新版修复了，新版过两天会发布。
