### ISSUE TITLE
一些功能优化建议

### ISSUE THREAD

**Issue by VitoYane** [yangjian102621/chatgpt-plus#173]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

- 众筹获取的条数, 与后台设置的值并没有对应起来
![image](https://github.com/yangjian102621/chatgpt-plus/assets/17432059/23791848-8a99-4b4c-a27a-3a7d562aaa47)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/17432059/d7db6422-a7c3-41bc-a174-90775391f90f)

- 没有条数之后, 提示的信息应该使用客服微信才是, 手动改了一下static里面的图片, 也没有生效. 不清楚原因
![9ddd30c14e616c21f82a4861b731ed2](https://github.com/yangjian102621/chatgpt-plus/assets/17432059/58499eb4-faa4-458c-8e2d-40bbb39c43fb)

### 动机 🔦

第一个问题: 众筹应该不是固定数值, 应该根据设置计算实际的值.
第二个问题: 如果所有的问题都找程序作者, 你应该也挺烦的吧

**Comment by yangjian102621** [comment]
1. 你可以上传没有限额的二维码收款图。
2. 客服二维码可以后台上传，旧代码有些问题，改了需要重启才生效。

**Comment by VitoYane** [comment]
> 1. 你可以上传没有限额的二维码收款图。
> 2. 客服二维码可以后台上传，旧代码有些问题，改了需要重启才生效。
你好, 多谢回复, 但是可能有点误解我的意思:
问题一: 我是上传的没有限额的二维码, 我的意思是, 提示信息"你好, 众筹9.9元, 获得100次对话"这个信息不对, 也没法改
问题二: 我重启了好几次了, 就是不引用我上传的二维码, 不过也没有特别大的影响就是

**Comment by yangjian102621** [comment]
收到，新版已经修复了次问题，近期会上线。
