### ISSUE TITLE
登录失败，Request failed with status code 502

### ISSUE THREAD

**Issue by jin2005006** [yangjian102621/chatgpt-plus#175]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

登录失败，Request failed with status code 502
![image](https://github.com/yangjian102621/chatgpt-plus/assets/30894558/f3fc4353-2c13-4e23-bb3c-3c26051ab871)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by jin2005006** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/30894558/098d42f3-2fba-4229-9b9c-22aec73d1e94)
按照文本里面的配置来的，还需要改什么东西么

**Comment by VitoYane** [comment]
https://github.com/yangjian102621/chatgpt-plus/issues/171
看下是不是这个问题, 扫码登录一下微信, 或者关掉 wechatbot 看还能不能登

**Comment by yangjian102621** [comment]
502 说明你的 API 应用没有启动成功。
