### ISSUE TITLE
获取系统配置失败：record not found

### ISSUE THREAD

**Issue by TecLuxking** [yangjian102621/chatgpt-plus#176]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

在CentOS中使用Docker部署了3.2.6版本，但是在docker-compose.yml文件中chatgpt-plus-api 和 chatgpt-plus-web 的版本号一直用的3.1.8.1。今天跟着安装部署文档中的平滑升级部分更新到3.2.6之后报这个错误。

### 重现步骤 🕹

1.运行了database里的update-v3.1.9.sql到update-v3.2.6.sql，中间有一些mysql报错。
![2024-03-25_152657](https://github.com/yangjian102621/chatgpt-plus/assets/28854623/55ac1766-0926-48cc-a99f-efbbef9968e5)
2.把yml文件中的版本号更改为了3.2.6-amd64
![2024-03-25_153703](https://github.com/yangjian102621/chatgpt-plus/assets/28854623/59db309b-bd0e-497b-8f17-1d5267f28af1)
3.重启容器之后打开网站登陆后在对话页面就报”获取系统配置失败：record not found“错误。
![2024-03-25_153958](https://github.com/yangjian102621/chatgpt-plus/assets/28854623/b0dd434e-ed4a-4a84-b5e6-5c52daef2808)
4.进入后台在系统设置处则会报”公告信息失败: record not found“。
![2024-03-25_154050](https://github.com/yangjian102621/chatgpt-plus/assets/28854623/198ea5d6-f2d5-46b4-a803-cb453caa1fdd)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/4746061/575a32be-eb6a-4cb7-a161-ca196c4e0192)

更新一下网站公告。
