### ISSUE TITLE
函数插件  今日热搜失败

### ISSUE THREAD

**Issue by lmq352489099** [yangjian102621/chatgpt-plus#182]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

根据文档 这边 操作

![image](https://github.com/yangjian102621/chatgpt-plus/assets/37898934/70fcabd4-94cc-4737-8b46-0de0b05ff62c)

然后前端展示
![image](https://github.com/yangjian102621/chatgpt-plus/assets/37898934/51a9631b-0e73-49ae-bad9-42e788782c57)

请问还需要操作什么

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
热搜服务依赖第三方的服务的，需要找作者获取 Token
