### ISSUE TITLE
使用MD绘画功能 报这个错误 如何解决

### ISSUE THREAD

**Issue by lmq352489099** [yangjian102621/chatgpt-plus#183]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

算力是扣除了但是图片没生成
![image](https://github.com/yangjian102621/chatgpt-plus/assets/37898934/a8913127-1896-4045-870e-e852df69b991)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/37898934/1a69aef2-81d2-4f86-ac2b-cb2043b14ac4)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
报错信息很明白，IP 地址没有授权。可能是你创建令牌的时候设置了 IP 白名单。
