### ISSUE TITLE
Midjourney生成的图，超过超时时间都会被删除掉

### ISSUE THREAD

**Issue by chunxiuxiamo** [yangjian102621/chatgpt-plus#184]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

![d6c7feba690308d6b831a490cd27932](https://github.com/yangjian102621/chatgpt-plus/assets/33317694/d564062b-791e-49ae-ab90-fd9bda0f258f)
任务超时的记录列表中，绘图成功后没有从记录中清掉，导致超过时间的图片都会被删除掉
![25a65e70401e56c8376968418d3440a](https://github.com/yangjian102621/chatgpt-plus/assets/33317694/3a07a8e3-e0de-449b-97a9-75ac0f0befeb)
上一个版本的mj是有判断进度所以没有表现出这个问题

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
新版已经修复这个 Bug 了
