### ISSUE TITLE
每次重启或者关闭都会出现提示

### ISSUE THREAD

**Issue by su16888** [yangjian102621/chatgpt-plus#185]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

cent的宝塔面板docker安装的
每次重启或者关闭都会出现提示
WARN[0000] /root/chatgpt-plus/docker-compose.yaml: `version` is obsolete

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
这个只是提示你用了旧版的 docker-compose，不用理会
