### ISSUE TITLE
新版需要授权？

### ISSUE THREAD

**Issue by weikecloud** [yangjian102621/chatgpt-plus#186]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-4

### 操作系统

Linux

### Bug 描述 📝

新版需要授权？

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
社区版都不需要的。稍后授权版的会另外建仓库的。

**Comment by weikecloud** [comment]
为什么我用一键搭建的命令，里面配置自己的中转会显示该api不在白名单中呢？

**Comment by gbkus123** [comment]
> 为什么我用一键搭建的命令，里面配置自己的中转会显示该api不在白名单中呢？

我也是 , 这么搞?

**Comment by momaek** [comment]
> 为什么我用一键搭建的命令，里面配置自己的中转会显示该api不在白名单中呢？

你解决这个问题了嘛？

**Comment by momaek** [comment]
> 为什么我用一键搭建的命令，里面配置自己的中转会显示该api不在白名单中呢？

你好，请问下，你解决这个问题了嘛？

**Comment by yangjian102621** [comment]
使用源码自己编译镜像的就不需要，用作者打包的最新的版镜像是需要授权的，那个是 PLUS 版本。
https://github.com/yangjian102621/geek-ai
