### ISSUE TITLE
部署成功后，仍然无法登录返回502错误

### ISSUE THREAD

**Issue by zuiyuewentian** [yangjian102621/chatgpt-plus#19]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

![image](https://github.com/yangjian102621/chatgpt-plus/assets/1026322/258ad15c-278f-48da-89d9-07a80ba828b3)
查看了docker日志，部署成功的，也没有报错，数据库也可以链接上去，就是登录时候一直报错502
![image](https://github.com/yangjian102621/chatgpt-plus/assets/1026322/5cb468f5-5bf4-434b-bb01-538405480fb8)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
解决方案请参考 #16
