### ISSUE TITLE
星火模型报错

### ISSUE THREAD

**Issue by kenputon1** [yangjian102621/chatgpt-plus#192]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

ERROR chatimpl/chat_handler.go:184 Recover message from error: runtime error: invalid memory address or nil pointer dereference，通义没问题，星火的无论什么版本都报错，只有这一句，apikey确定没问题，顺序也是对的

### 重现步骤 🕹

配置星火模型api，使用，无响应，日志报错

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
你的 API 地址是不是自己手填的？

**Comment by yinmao** [comment]
同样的问题，API URL保持wss://spark-api.xf-yun.com/{version}/chat不变或修改为wss://spark-api.xf-yun.com/v3.5/chat都报错：`2024-05-03T13:41:52.193+0800	INFO	chatimpl/chat_handler.go:162	Receive a message: hi
2024-05-03T13:41:52.379+0800	ERROR	chatimpl/chat_handler.go:184	Recover message from error: runtime error: invalid memory address or nil pointer dereference
2024-05-03T13:41:52.379+0800	INFO	chatimpl/chat_handler.go:173	回答完毕: hi`

**Comment by thisisdun998** [comment]
我有出现同样的问题，请问现在有解决吗？ @yinmao

**Comment by yangjian102621** [comment]
更新到4.0.4 可以解决

<img width="1003" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/4746061/10535ac2-e701-4177-8676-2df58309f403">
