### ISSUE TITLE
接入通义千问模型之后，调用第一次对话没问题，第二次对话就不会回复了

### ISSUE THREAD

**Issue by ly1217wxm** [yangjian102621/chatgpt-plus#197]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

接入了官方的通义千问模型之后，第一次对话会正常回复，然后再对话就没有任何回复了

### 重现步骤 🕹

接入通义千问模型，调用
![1715676581884](https://github.com/yangjian102621/chatgpt-plus/assets/157621442/d6003c69-b05d-468b-96f1-e613a2a80ece)
![1715677116134](https://github.com/yangjian102621/chatgpt-plus/assets/157621442/f324fa2a-0c09-4dcd-91fe-b4a0335c1955)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
更新到最 4.0.4 版本
