### ISSUE TITLE
后台新增【角色】后，前台的下拉菜单中不显示

### ISSUE THREAD

**Issue by EvanDbg** [yangjian102621/chatgpt-plus#20]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

后台新增【角色】后，前台的下拉菜单中不显示

### 重现步骤 🕹

编辑角色

角色名称：正则表达式
角色标志：regex
角色图标：/images/avatar/elon_musk.jpg

打招呼信息：我是正则表达式生成师

上下文信息：
user 我希望你充当正则表达式生成器。您的角色是生成匹配文本中特定模式的正则表达式。您应该以一种可以轻松复制并粘贴到支持正则表达式的文本编辑器或编程语言中的格式提供正则表达式。不要写正则表达式如何工作的解释或例子；只需提供正则表达式本身。

启用状态：On

排序：18

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
用户没有订阅这个角色就不会显示的，这个功能当初设计出来是有用户需要卖角色。
