### ISSUE TITLE
【建议】给可以每个用户设置GPT 模型范围

### ISSUE THREAD

**Issue by EvanDbg** [yangjian102621/chatgpt-plus#22]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

给可以每个用户设置GPT 模型范围，方便对用户权限进行管理。

### 示例 🌈

高级用户：gpt-4-Mobile, gpt-4, gpt-3.5
普通用户：gpt-3.5

### 动机 🔦

一部分高级用户享用Gpt4 普通用户就用gpt3.5
控制成本

**Comment by yangjian102621** [comment]
系统没有高级用户和普通用户的区分，目前没有付费用户都是免费的，后期如果要收费的话，就会区分了。
