### ISSUE TITLE
聊天界面，建议加个醒目的切换角色列表的文案标识。否则用户第一眼不知道那个select框的作用

### ISSUE THREAD

**Issue by msh01** [yangjian102621/chatgpt-plus#23]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

如图
![image](https://github.com/yangjian102621/chatgpt-plus/assets/5895871/67e43563-6567-464e-b477-c7d7ca919c44)

**Comment by yangjian102621** [comment]
v3.0.5 已经解决这个问题了。
