### ISSUE TITLE
本地部署报错 404 

### ISSUE THREAD

**Issue by hieivip** [yangjian102621/chatgpt-plus#25]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

后端路径：“http://localhost:8888/admin/login

前端路径：http://localhost:8888/login  
看了之前有人提过的问题，说前端路径应该是 http://localhost:8888/chat       访问这个直接跳转到了 http://localhost:8888/login

不知道是我哪里启动的问题

本地数据库 ，本地 go语言环境；  开发工具 vscode      

### 你的应用配置信息

Listen = "0.0.0.0:5678"
ProxyURL = ""
MysqlDns = "root:123456aA@tcp(127.0.0.1:3306)/chatgpt_plus?charset=utf8&parseTime=True&loc=Local"
StaticDir = "./static"
StaticUrl = "http://localhost/5678/static"

[Session]
  Driver = "cookie"
  SecretKey = "m0utpsyxjkl5ekgvyiqzmxnrvbdfkv781x6d2baldr56kla8njfa2mtpjocomo0y"
  Name = "CHAT_PLUS_SESSION"
  Path = "/"
  Domain = ""
  MaxAge = 86400
  Secure = true
  HttpOnly = false
  SameSite = 2

[Manager]
  Username = "admin"
  Password = "admin123"

[Redis]
  Host = "localhost"
  Port = 6379
  Password = ""
-------------------------------------------------------------------------------------------------------------

.env.production  配置信息

VUE_APP_API_HOST=http://localhost:5678
VUE_APP_WS_HOST=http://localhost:5678
VUE_APP_BASE_URL=

**Comment by hieiip1203** [comment]
是不是因为没有 make all 导致的？？？

**Comment by hieivip** [comment]
已经可以解决 404问题了，发现了下个问题   
获取用户角色失败
![image](https://github.com/yangjian102621/chatgpt-plus/assets/54146330/512f230f-0b6e-44b2-8135-38eedfaa340e)

后台用户管理：
![image](https://github.com/yangjian102621/chatgpt-plus/assets/54146330/4ac67302-dce9-4e51-9ce9-4e3922a7d909)
后台角色管理：
![image](https://github.com/yangjian102621/chatgpt-plus/assets/54146330/ca209cd1-c5ca-4502-8c3f-0fe4a35fccf1)
系统设置管理：
![image](https://github.com/yangjian102621/chatgpt-plus/assets/54146330/ba6e8597-63ac-4820-a9da-8ae7ec415108)

请问我是哪里设置有问题吗？

**Comment by hieivip** [comment]
补充审查元素

![image](https://github.com/yangjian102621/chatgpt-plus/assets/54146330/71bc4092-e50f-41cf-801e-0a3c24ed8f42)

vcode 后端数据日志 
![image](https://github.com/yangjian102621/chatgpt-plus/assets/54146330/bc503df2-4c8c-4384-9321-698d143ff389)

vcode 前端数据日志

![image](https://github.com/yangjian102621/chatgpt-plus/assets/54146330/1945d2b3-cca5-4067-b70a-771b60c7a341)


各位大佬 看看到底哪里出问题了。搞晕乎了

**Comment by yangjian102621** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/4746061/202108eb-45cf-4584-881a-983ac6109380)

**Comment by hieivip** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/54146330/a334046f-08fe-469b-81a3-fb1d2c2af838)
修改了配置文件及端口，还是无法获取角色

-------------------------------------------------------------------------
Listen = "0.0.0.0:5678"
ProxyURL = ""
MysqlDns = "chatgptplus:chatgptplus@tcp(localhost:3306)/chatgptplus?charset=utf8&parseTime=True&loc=Local"

[Session]
  SecretKey = "azyehq3ivunjhbntz78isj00i4hz2mt9xtddysfucxakadq4qbfrt0b7q3lnvg80"
  Name = "CHAT_SESSION_ID"
  Path = "/"
  Domain = ""
  MaxAge = 86400
  Secure = false
  HttpOnly = false
  SameSite = 2

[Manager]
  Username = "admin"
  Password = "admin123"
-----------------------------------------------------------------------------
web配置文件
VUE_APP_API_HOST=http://localhost:5678
VUE_APP_WS_HOST=http://localhost:5678
VUE_APP_BASE_URL=

大神 实在不知道哪里出问题，直接提示“获取角色失败”，F12 没有发现任何404问题
![image](https://github.com/yangjian102621/chatgpt-plus/assets/54146330/08662038-b607-47f1-b218-63bdc9781563)

**Comment by hieivip** [comment]
补充：
![image](https://github.com/yangjian102621/chatgpt-plus/assets/54146330/7d5e9667-9309-4f16-97e5-9b2c9211862d)

**Comment by yangjian102621** [comment]
@hieivip 可能是数据库的历史数据数据结构的问题，尝试修复一下数据结构，一次访问下面的几个 API：
```bash
http://localhost:5678/api/admin/migrate?opt=user
http://localhost:5678/api/admin/migrate?opt=role
http://localhost:5678/api/admin/migrate?opt=history
http://localhost:5678/api/admin/migrate?opt=avatar
```
记住，只执行一次就好了。

**Comment by hyrhyrh** [comment]
朋友方便加个联系方式，请教下windows部署的问题吗
