### ISSUE TITLE
websocket连接不上

### ISSUE THREAD

**Issue by cmkcmk181** [yangjian102621/chatgpt-plus#26]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

前端登录后(http://127.0.0.1:8888/chat)，无法连接后端websocket。判断应该是后端websocket不生效。

### 重现步骤 🕹

1.登录http://127.0.0.1:8888/chat
2.加载后，右边遮罩无法关闭。控制台websocket连接报错。

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
请提供更详细的信息，比如你是用什么方式部署的？docker 还是本地调试开发模式？前后端的配置是怎样的？
