### ISSUE TITLE
Field 'mobile' doesn't have a default value

### ISSUE THREAD

**Issue by koblise** [yangjian102621/chatgpt-plus#27]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

登录时提示
2023/07/29 17:48:38 /golang/src/chatgpt-plus/api/go/handler/user_handler.go:98 Error 1364 (HY000): Field 'mobile' doesn't have a default value
看了数据库有默认值

### 重现步骤 🕹

按照文档部署

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```
Listen = "0.0.0.0:5678"
ProxyURL = "http://172.22.11.200:7777"
MysqlDns = "root:xx@tcp(localhost:3306)/chatgpt_plus?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local"
StaticDir = "./static"
StaticUrl = "http://localhost:5678/static"
AesEncryptKey = "{YOUR_AES_KEY}"
StartWechatBot = false
EnabledMsgService = false

[Session]
  Driver = "cookie"
  SecretKey = "m0cjm3gsuw9jk73np1ni7r42koilybjcndlycjdmq7za3pbqn7w12fyok5pqh"
  Name = "CHAT_SESSION_ID"
  Path = "/"
  Domain = "localhost"
  MaxAge = 86400
  Secure = false
  HttpOnly = false
  SameSite = 2

[Manager]
  Username = "admin"
  Password = "admin12345"

[Redis]
  Host = "localhost"
  Port = 6379

**Comment by yangjian102621** [comment]
代码更新到最新的版本试下。v3.0.5
