### ISSUE TITLE
编译部署后无法登录管理员后台

### ISSUE THREAD

**Issue by koblise** [yangjian102621/chatgpt-plus#28]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

![image](https://github.com/yangjian102621/chatgpt-plus/assets/77476588/f44effbc-3f20-4ddf-be56-a4b2339e48f2)
编译部署完成后无法连接后端，显示{"code":400,"message":"Not Authorized"}
多次尝试后还是无法登录

### 你的应用配置信息

server {
    listen  8080;
    server_name  www.chatgpt.com; #替换成你自己的域名

    #ssl_certificate     xxx.pem;  # 替换成自己的 SSL 证书
    #ssl_certificate_key  xxx.key;
    #ssl_session_timeout  5m;
    #ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    #ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    #ssl_prefer_server_ciphers on;
    
    # 日志地址
    access_log  /var/log/chatgpt/access.log;
    error_log /var/log/chatgpt/error.log;
    
    index index.html;
    root /var/www/chatgpt/dist; # 这里改成前端静态页面的地址

    location / {
        try_files $uri $uri/ /index.html;
        
         # 后端 API 的转发
        location /api/ {
                proxy_http_version 1.1;
                proxy_connect_timeout 300s;
                proxy_read_timeout 300s;
                proxy_send_timeout 12s;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_pass http://ip:5678; # 这里改成后端服务的内网 IP 地址 
        }

        # 静态资源转发
        location /static/ {
            proxy_pass http://ip:5678; # 这里改成后端服务的内网 IP 地址
        }
    }
    
}

**Comment by yangjian102621** [comment]
@koblise 你 nginx 配置有问题，建议看下视频教程。https://www.bilibili.com/video/BV1H14y1B7Qw/
