### ISSUE TITLE
看功能介绍有微信支付宝支付，但是本地运行起来没看到。

### ISSUE THREAD

**Issue by torome** [yangjian102621/chatgpt-plus#29]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

支付功能是否是配置问题吗，还是目前没有这个功能

### 示例 🌈

界面上没看到

### 动机 🔦

服务于我微信群的粉丝，考虑运营成本，需要有一定的付费

**Comment by yangjian102621** [comment]
要启用支付功能的话，首先需要在配置文档中启用微信机器人，然后在日志中通过微信扫码登录。
