### ISSUE TITLE
部署完成后登录控制台不跳转仪表盘

### ISSUE THREAD

**Issue by longtiequan** [yangjian102621/chatgpt-plus#30]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

更新到3.0.6.3后登录后台，输入正确的账号密码后不跳转到仪表盘；还有就是关于导入数据库文件的问题，我应该导入哪个sql文件？您目前/database目录下有两个sql文件，一个update和一个chatplus的文件，导入这两个有什么区别吗？感谢您的解答

### 重现步骤 🕹

![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/878d4ead-cd36-41c4-9810-fa883d5dce5f)
这是输入正确的账号密码后，点击登录没反应
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/e3dc1c6a-5d79-4f25-8c7c-57ba280100a0)
这是输入错误的账号密码后的界面

### 你的应用配置信息

![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/42365c7d-8f9c-422c-a03c-8b1a544fd4cf)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/e6159903-594a-492f-9363-2cccef775792)

**Comment by longtiequan** [comment]
补充一些信息，我是用docker部署的，并且手动将版本更新到了3.0.6.3，确定后台都是在正常启动的
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/3f07f026-a56a-4792-9873-4b9f52e02d12)

**Comment by yangjian102621** [comment]
最好把你浏览器和控制台的报错信息截图贴出来，目前你提供的信息只能证明你的服务启动成功了。没有有效的排查信息。

**Comment by longtiequan** [comment]
好的好的，我忘了看浏览器报错信息了
![ba325711c533cf1f127a1ed99c87c98](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/82a35940-dd47-4eb3-aeb0-7c34dc33c146)
![8b11777a16a903d416d07e64642e561](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/3bb87f56-6e4e-45ae-9fac-088028a68574)
我用过chrome浏览器，报错应该都是一样的

**Comment by yangjian102621** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/4746061/03afb655-7477-4283-8f3f-f9706cbc1f39)

删除 login.vue 文件 trim  代码，然后看下后端是否也报错了。

**Comment by longtiequan** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/9bd40fc5-d9d1-4142-ba95-1572618b5e04)
这样注释掉就可以了是吧？后端报错在哪里看呢？

**Comment by longtiequan** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/8c6822ce-f5b5-4e15-8796-51b03f8e6c7c)

现在前端浏览器倒是没有报错了，但是还是没办法跳转，我重启过几次服务了，后端报错在哪里看呢？

**Comment by yangjian102621** [comment]
就是其看看你后端的运行日志，看下日志里面有没有报错。

**Comment by longtiequan** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/c26bc115-c15c-4409-a788-bfe43216a5bc)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/a9d3b27b-9bce-4a42-ac04-b185ae231492)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/91169d95-e788-4e47-b3aa-68aa04009f6a)

我又重新部署了一遍，还是不跳转，后端日志是这些吗？

**Comment by yangjian102621** [comment]
看下浏览器调试面板的 console 和 network ，看下后端 API 返回的数据是什么。然后就是看下 console 有没有 报错信息。

**Comment by longtiequan** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/130081312/e1ba0e93-ebf8-45a7-8d9d-2c5585584eb2)
console里面没有报错，network里面这个400未授权有关系吗？
