### ISSUE TITLE
输入正确账号密码后没有反应

### ISSUE THREAD

**Issue by yangbig730** [yangjian102621/chatgpt-plus#31]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

输入账号密码后，登录没有反应，浏览器提示
![image](https://github.com/yangjian102621/chatgpt-plus/assets/57706271/b7392693-a0bf-4c3c-87af-9c59ee6124ac)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangbig730** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/57706271/e2cd65f9-f76c-4d10-a08b-79aad438c1e1)
注册用户的时候提示字段错误

**Comment by yangjian102621** [comment]
把 chatgpt_users 数据表的 mobile 字段设置一个默认值
