### ISSUE TITLE
服务器上docker部署的， 用本地浏览器访问报400错误

### ISSUE THREAD

**Issue by WSL12131415** [yangjian102621/chatgpt-plus#32]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

如题 纯小白一只，烦请大佬解答！、
![7022946de3b03d92eac9fbd431184d5](https://github.com/yangjian102621/chatgpt-plus/assets/121419347/a5499cb0-4c16-445f-b88f-876b8734b526)
![54c00fedaa9012febe8330b19bc62e4](https://github.com/yangjian102621/chatgpt-plus/assets/121419347/07616104-da3f-4a83-9415-14994d3f321a)
![微信截图_20230819002518](https://github.com/yangjian102621/chatgpt-plus/assets/121419347/6433feef-6254-4fb3-8496-d7baa9c05da9)
![微信截图_20230819002546](https://github.com/yangjian102621/chatgpt-plus/assets/121419347/ead66a49-ff35-44a6-a1af-bbf4dd2753ad)

### 重现步骤 🕹

按照b站视频教程部署，就是进页面就闪退回主页面

### 你的应用配置信息

  # 后端 API 的转发
        location /api/ {
                proxy_http_version 1.1;
                proxy_connect_timeout 300s;
                proxy_read_timeout 300s;
                proxy_send_timeout 12s;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_pass http://101.37.167.132:5678; # 这里改成后端服务的内网 IP 地址
        }

        # 静态资源转发
        location /static/ {
            proxy_pass http://101.37.167.132:5678; # 这里改成后端服务的内网 IP 地址
        }
    }
}

Listen = "0.0.0.0:5678"
ProxyURL = "http://127.0.0.1:7777"
MysqlDns = "root:12345678@tcp(101.37.167.132:3307)/chatgpt_plus?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local"
StaticDir = "./static"
StaticUrl = "/static"
AesEncryptKey = "{YOUR_AES_KEY}"
StartWechatBot = false
EnabledMsgService = false

**Comment by WSL12131415** [comment]
配置文件是这样的
Listen = "0.0.0.0:5678"
ProxyURL = "http://127.0.0.1:7777"
MysqlDns = "root:12345678@tcp(101.37.167.132:3307)/chatgpt_plus?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local"
StaticDir = "./static"
StaticUrl = "/static"
AesEncryptKey = "{YOUR_AES_KEY}"
StartWechatBot = false
EnabledMsgService = false

[Session]
  Driver = "cookie"
  SecretKey = "m0cjm3gsuw9jk73np1ni7r42koilybjcndlycjdmq7za3pbqn7w12fyok5pqh6q5"
  Name = "CHAT_SESSION_ID"
  Path = "/"
  Domain = ""
  MaxAge = 86400
  Secure = true
  HttpOnly = false
  SameSite = 2

**Comment by yangjian102621** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/4746061/41590138-f1a8-47d4-83f2-cd3e386b6cd3)

如果你用 IP 访问的话，那么这里就配置你允许跨域的 IP

**Comment by yanguo0905** [comment]
> ### ⚠️ 确认 issue 是否已存在 ⚠️
> * [x]  我已经搜索了现有的问题，没有找到跟我问题相关的问题。
> 
> ### GPT-3 or GPT-4
> GPT-3.5
> 
> ### 操作系统
> Windows
> 
> ### Bug 描述 📝
> 如题 纯小白一只，烦请大佬解答！、 ![7022946de3b03d92eac9fbd431184d5](https://user-images.githubusercontent.com/121419347/261661528-a5499cb0-4c16-445f-b88f-876b8734b526.png) ![54c00fedaa9012febe8330b19bc62e4](https://user-images.githubusercontent.com/121419347/261661547-07616104-da3f-4a83-9415-14994d3f321a.png) ![微信截图_20230819002518](https://user-images.githubusercontent.com/121419347/261661568-6433feef-6254-4fb3-8496-d7baa9c05da9.png) ![微信截图_20230819002546](https://user-images.githubusercontent.com/121419347/261661573-ead66a49-ff35-44a6-a1af-bbf4dd2753ad.png)
> 
> ### 重现步骤 🕹
> 按照b站视频教程部署，就是进页面就闪退回主页面
> 
> ### 你的应用配置信息
> # 后端 API 的转发
> ```
>     location /api/ {
>             proxy_http_version 1.1;
>             proxy_connect_timeout 300s;
>             proxy_read_timeout 300s;
>             proxy_send_timeout 12s;
>             proxy_set_header Host $host;
>             proxy_set_header X-Real-IP $remote_addr;
>             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>             proxy_set_header Upgrade $http_upgrade;
>             proxy_set_header Connection $connection_upgrade;
>             proxy_pass http://101.37.167.132:5678; # 这里改成后端服务的内网 IP 地址
>     }
> 
>     # 静态资源转发
>     location /static/ {
>         proxy_pass http://101.37.167.132:5678; # 这里改成后端服务的内网 IP 地址
>     }
> }
> ```
> 
> }
> 
> Listen = "0.0.0.0:5678" ProxyURL = "http://127.0.0.1:7777" MysqlDns = "root:12345678@tcp(101.37.167.132:3307)/chatgpt_plus?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=True&loc=Local" StaticDir = "./static" StaticUrl = "/static" AesEncryptKey = "{YOUR_AES_KEY}" StartWechatBot = false EnabledMsgService = false

能不能发一下B站视频教程链接？

**Comment by yangjian102621** [comment]
请参考最新的部署文档进行部署：[https://ai.r9it.com/docs/](https://ai.r9it.com/docs/)
