### ISSUE TITLE
镜像地址失效了，建议上传到docker.io

### ISSUE THREAD

**Issue by luowei729** [yangjian102621/chatgpt-plus#34]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

registry.cn-hangzhou.aliyuncs.com/

### 重现步骤 🕹

docker-compose up -d
Pulling chatgpt-plus-api (registry.cn-hangzhou.aliyuncs.com/geekmaster/chatgpt-plus-api:v3.0.5.2)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```
docker-compose up -d
Pulling chatgpt-plus-api (registry.cn-hangzhou.aliyuncs.com/geekmaster/chatgpt-plus-api:v3.0.5.2)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

**Comment by yangjian102621** [comment]
旧版本的地址是失效了，建议使用最新版本。

**Comment by dfggggx198601** [comment]
这个最新版本3.0.7.4也是不存在

**Comment by chaosye0** [comment]
同样的问题

**Comment by yangjian102621** [comment]
阿里云限流了，所以目前不提供镜像下载了，大家可以自己编译打包，打包教程参考文档 https://ai.r9it.com/docs/deploy/build.html。
