### ISSUE TITLE
使用arm64架构对api进行打包编译，制作镜像运行容器后，访问主页为空白页，访问容器日志无提示报错

### ISSUE THREAD

**Issue by dfggggx198601** [yangjian102621/chatgpt-plus#36]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

使用arm64架构对api进行打包编译，制作镜像运行容器后，访问主页为空白页，访问容器日志无提示报错
![image](https://github.com/yangjian102621/chatgpt-plus/assets/104133292/7b5b9ee6-0546-4b86-83ec-cd11b92827f7)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/104133292/256c7f7c-4d95-49bc-a2b2-747f7b74ada9)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/104133292/29af606a-497c-415e-976f-fbd0d45c9d92)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/104133292/4049dd1d-fc4a-4fec-acf3-1ca1ff134b15)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
1. 请提供你的 docker-compose.yaml 文件
2. 请提供浏览器控制台的报错信息，以及浏览器调试面板的 API 网络请求的返回信息。
3. 因为你后端配置的公网 IP不是内网 IP，所以请确保你的 5678 和 8081 端口对公网是开放的。

**Comment by dfggggx198601** [comment]
解决了，原来是因为下载了源码后，没有先进行编译，导致build的时候，nginx挂载的目录少了文件。
