### ISSUE TITLE
无法进行用户注册，返回错误信息，

### ISSUE THREAD

**Issue by dfggggx198601** [yangjian102621/chatgpt-plus#37]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

![image](https://github.com/yangjian102621/chatgpt-plus/assets/104133292/7c105cdc-6bfe-4a23-9546-3afe0343f477)
请看图，在admin面板中可以增加用户，用户自行注册就不行了

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by jy00566722** [comment]
临时解决方案:在web/src/views/Register.vue中:
`const formData = ref({
  mobile: '',
  password: '',
  code: '',
  repass: '',
})`

把code:'',改为code:0,
因为如果为空的话，后端序列化时出错，直接返回错误。

**Comment by dfggggx198601** [comment]
非常感谢，我开始怎么也想不到是改这里，以为是改api下面的相关代码

**Comment by yangjian102621** [comment]
这个 Bug 将在 v3.1.4 版本中修复。
