### ISSUE TITLE
请问下平台支持文心一言的接入吗?

### ISSUE THREAD

**Issue by papandadj** [yangjian102621/chatgpt-plus#38]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

我看了下平台readme有介绍说支持文心一言，但是我在添加key的时候没找到文心一言的添加方式。想问下平台支持文心一言的接入吗？

**Comment by yangjian102621** [comment]
还没有支持接入，预计在下下个版本也就是 v3.1.5 中支持，目前正在接入 StableDiffusion 绘图。

**Comment by papandadj** [comment]
好的，我看下，能不能贡献下力

**Comment by yangjian102621** [comment]
@papandadj 文心一言和科大讯飞 API 已接入。 具体更新请看 [CHANGELOG](https://github.com/yangjian102621/chatgpt-plus/blob/main/CHANGELOG.md#v315)
