### ISSUE TITLE
运行api报错

### ISSUE THREAD

**Issue by huicewang** [yangjian102621/chatgpt-plus#40]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

运行 go run main.go报错如下：
[Fx] ERROR              fx.Invoke(main.main.func3()) called from:
main.main
        /root/chatgpt-plus/api/main.go:88
runtime.main
        /usr/lib/go-1.20/src/runtime/proc.go:250
Failed: could not build arguments for function "main".main.func3
        /root/chatgpt-plus/api/main.go:88:
failed to build *core.AppServer:
could not build arguments for function "chatplus/core".NewServer
        /root/chatgpt-plus/api/core/app_server.go:39:
failed to build map[string]fun.Function:
could not build arguments for function "chatplus/service/fun".NewFunctions
        /root/chatgpt-plus/api/service/fun/function.go:32:
failed to build *mj.Service:
could not build arguments for function "chatplus/service/mj".NewService
        /root/chatgpt-plus/api/service/mj/service.go:33:
failed to build *redis.Client:
received non-nil error from function "chatplus/store".NewRedisClient
        /root/chatgpt-plus/api/store/redis.go:10:
read tcp [::1]:42976->[::1]:6379: read: connection reset by peer
[Fx] ERROR              Failed to start: could not build arguments for function "main".main.func3
        /root/chatgpt-plus/api/main.go:88:
failed to build *core.AppServer:
could not build arguments for function "chatplus/core".NewServer
        /root/chatgpt-plus/api/core/app_server.go:39:
failed to build map[string]fun.Function:
could not build arguments for function "chatplus/service/fun".NewFunctions
        /root/chatgpt-plus/api/service/fun/function.go:32:
failed to build *mj.Service:
could not build arguments for function "chatplus/service/mj".NewService
        /root/chatgpt-plus/api/service/mj/service.go:33:
failed to build *redis.Client:
received non-nil error from function "chatplus/store".NewRedisClient
        /root/chatgpt-plus/api/store/redis.go:10:
read tcp [::1]:42976->[::1]:6379: read: connection reset by peer
2023/10/11 11:51:19 could not build arguments for function "main".main.func3 (/root/chatgpt-plus/api/main.go:88): failed to build *core.AppServer: could not build arguments for function "chatplus/core".NewServer (/root/chatgpt-plus/api/core/app_server.go:39): failed to build map[string]fun.Function: could not build arguments for function "chatplus/service/fun".NewFunctions (/root/chatgpt-plus/api/service/fun/function.go:32): failed to build *mj.Service: could not build arguments for function "chatplus/service/mj".NewService (/root/chatgpt-plus/api/service/mj/service.go:33): failed to build *redis.Client: received non-nil error from function "chatplus/store".NewRedisClient (/root/chatgpt-plus/api/store/redis.go:10): read tcp [::1]:42976->[::1]:6379: read: connection reset by peer
exit status 1

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```
Listen = "0.0.0.0:5678"
ProxyURL = "" # 如 http://127.0.0.1:7777
MysqlDns = "root:12345678@tcp(mysql:3306)/chatgpt_plus?charset=utf8&parseTime=True&loc=Local"
StaticDir = "./static" # 静态资源的目录
StaticUrl = "/static" # 静态资源访问 URL
AesEncryptKey = ""
WeChatBot = false

[Session]
  SecretKey = "azyehq3ivunjhbntz78isj00i4hz2mt9xtddysfucxakadq4qbfrt0b7q3lnvg80" # 注意：这个是 JWT Token 授权密钥，生产环境请务必更换
  MaxAge = 86400

[Manager]
  Username = "admin"
  Password = "65132090" # 如果是生产环境的话，这里管理员的密码记得修改

[Redis] # redis 配置信息
  Host = "localhost"
  Port = 6379
  Password = ""
  DB = 0

[ApiConfig] # 微博热搜，今日头条等函数服务 API 配置，此为第三方插件服务，如需使用请联系作者开通
  ApiURL = ""
  AppId = ""
  Token = ""

[SmsConfig] # 阿里云短信服务配置
  AccessKey = ""
  AccessSecret = ""
  Product = "Dysmsapi"
  Domain = "dysmsapi.aliyuncs.com"
  Sign = ""
  CodeTempId = ""

[ExtConfig] # MidJourney和微信机器人服务 API 配置，开通此功能需要配合 chatpgt-plus-exts 项目部署
  ApiURL = "" # 插件扩展 API 地址
  Token = "" # 这个 token 随便填，只要确保跟 chatgpt-plus-exts 项目的 token 一样就行

[OSS] # OSS 配置，用于存储 MJ 绘画图片
   Active = "local" # 默认使用本地文件存储引擎
   [OSS.Local]
     BasePath = "./static/upload" # 本地文件上传根路径
     BaseURL = "http://localhost:5678/static/upload" # 本地上传文件根 URL 如果是线上，则直接设置为 /static/upload 即可
   [OSS.Minio]
     Endpoint = "" # 如 172.22.11.200:9000
     AccessKey = "" # 自己去 Minio 控制台去创建一个 Access Key
     AccessSecret = ""
     Bucket = "chatgpt-plus" # 替换为你自己创建的 Bucket，注意要给 Bucket 设置公开的读权限，否则会出现图片无法显示。
     UseSSL = false
     Domain = "" # 地址必须是能够通过公网访问的，否则会出现图片无法显示。
   [OSS.QiNiu] # 七牛云 OSS 配置
       Zone = "z2" # 区域，z0：华东，z1: 华北，na0：北美，as0：新加坡
       AccessKey = ""
       AccessSecret = ""
       Bucket = ""
       Domain = "" # OSS Bucket 所绑定的域名，如 https://img.r9it.com

[MjConfig]
  Enabled = false
  UserToken = ""
  BotToken = ""
  GuildId = ""
  ChanelId = ""

[SdConfig]
  Enabled = false
  ApiURL = "http://172.22.11.200:7860"
  ApiKey = ""
  Txt2ImgJsonPath = "res/text2img.json"

**Comment by yangjian102621** [comment]
日志里面有明显的报错提示，redis 连接不上，自己本地安装 redis-server 或者部署 redis 容器皆可。

**Comment by xiaowanzier** [comment]
你好，请问这个问题解决了吗，我也遇到了同样的问题
