### ISSUE TITLE
阿里云服务器部署时公网ip无法访问

### ISSUE THREAD

**Issue by fangzheng123** [yangjian102621/chatgpt-plus#41]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

参考了

- https://github.com/yangjian102621/chatgpt-plus/issues/8
- https://github.com/yangjian102621/chatgpt-plus/issues/19

等配置，均无法使用公网IP访问，报错超时无法访问。
在阿里云服务器上curl http://localhost:8080/chat有结果，查看容器日志也都启动成功，但换成http://公网ip:8080/chat时则访问超时，且已确认将服务器8080端口对外开放。
想请教一下仅修改配置是无法生效嘛，是需要修改哪个地方代码，重新编译后才能用公网ip访问嘛。

### 重现步骤 🕹

- 尝试将所有内网ip替换成公网ip仍然无效

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

使用容器版本v3.1.4：

chatgpt-plus.conf配置如下：
map $http_upgrade $connection_upgrade {
     default upgrade;
     'websocket'      upgrade;
}
server {
    listen 8080;
    server_name  公网ip; 

    access_log  /var/log/access.log;
    error_log /var/log/error.log;

    index index.html;
    root /var/www/app/dist; 

    location / {
        try_files $uri $uri/ /index.html;

        location /api/ {
                proxy_http_version 1.1;
                proxy_connect_timeout 300s;
                proxy_read_timeout 300s;
                proxy_send_timeout 12s;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_pass http://公网ip:5678; # 这里改成后端服务的内网 IP 地址
        }
        location /static/ {
            proxy_pass http://公网ip:5678; # 这里改成后端服务的内网 IP 地址
        }
    }
}

config.toml配置如下：
Listen = "0.0.0.0:5678"
ProxyURL = "http://公网ip:7777" # 如 http://127.0.0.1:7777
MysqlDns = "root:12345678@tcp(公网ip:3307)/chatgpt_plus?charset=utf8&parseTime=True&loc=Local"
StaticDir = "./static" # 静态资源的目录
StaticUrl = "/static" # 静态资源访问 URL
AesEncryptKey = ""
WeChatBot = false

[Session]
  SecretKey = "azyehq3ivunjhbntz78isj00i4hz2mt9xtddysfucxakadq4qbfrt0b7q3lnvg80" # 注意：这个是 JWT Token 授权密钥，生产环境请务必更换
  MaxAge = 86400
  Domain = "公网ip"
  Secure = false
  HttpOnly = false

[Manager]
  Username = "admin"
  Password = "admin123" # 如果是生产环境的话，这里管理员的密码记得修改

[Redis] # redis 配置信息
  Host = "公网ip"
  Port = 6379
  Password = ""
  DB = 0

.env.development配置：
VUE_APP_API_HOST=http://公网ip:5678
VUE_APP_WS_HOST=ws://公网ip:5678
VUE_APP_USER=18575670125
VUE_APP_PASS=12345678
VUE_APP_ADMIN_USER=admin
VUE_APP_ADMIN_PASS=admin123
VUE_APP_KEY_PREFIX=ChatPLUS_DEV_
VUE_APP_TITLE="ChatGPT-PLUS V3"

.env.production配置：
VUE_APP_API_HOST=http://公网ip:5678
VUE_APP_WS_HOST=http://公网ip:5678
VUE_APP_KEY_PREFIX=ChatPLUS_
VUE_APP_TITLE="ChatGPT-PLUS V3"

**Comment by yangjian102621** [comment]
使用公网 IP 访问，如果是通过容器部署的话，除了 nginx 的 server_name 需要配置公网成公网 IP，其他配置都设置成内网 IP 即可。另外，.env.production 配置保持默认即可，无需改动。

**Comment by fangzheng123** [comment]
您好，按照您说的进行配置，除了 nginx 的 server_name 配置成公网ip，其他配置均设置成内网ip了，.env.production 配置保持默认。仍然不行，无法使用公网访问到。

使用容器版本v3.1.4：

容器启动截图：
![WX20231012-155926@2x](https://github.com/yangjian102621/chatgpt-plus/assets/11494089/c6a4b888-59b2-4dd0-9ed0-4358d24f7fed)


相关配置如下：

config.toml
Listen = "0.0.0.0:5678"
ProxyURL = "http://内网ip:7777" # 如 http://127.0.0.1:7777
MysqlDns = "root:12345678@tcp(内网ip:3307)/chatgpt_plus?charset=utf8&parseTime=True&loc=Local"
StaticDir = "./static" # 静态资源的目录
StaticUrl = "/static" # 静态资源访问 URL
AesEncryptKey = ""
WeChatBot = false

[Session]
  SecretKey = "azyehq3ivunjhbntz78isj00i4hz2mt9xtddysfucxakadq4qbfrt0b7q3lnvg80" # 注意：这个是 JWT Token 授权密钥，生产环境请务必更换
  MaxAge = 86400
  Domain = "内网ip"
  Secure = false
  HttpOnly = false

[Manager]
  Username = "admin"
  Password = "admin123" # 如果是生产环境的话，这里管理员的密码记得修改

[Redis] # redis 配置信息
  Host = "内网ip"
  Port = 6379
  Password = ""
  DB = 0

chatgpt-plus.conf:
listen 8080;
server_name  公网ip; #替换成你自己的域名
location /api/ {
                proxy_http_version 1.1;
                proxy_connect_timeout 300s;
                proxy_read_timeout 300s;
                proxy_send_timeout 12s;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_pass http://内网ip:5678; # 这里改成后端服务的内网 IP 地址
        }

location /static/ {
      proxy_pass http://内网ip:5678; # 这里改成后端服务的内网 IP 地址
}
        

.env.development:
VUE_APP_API_HOST=http://内网ip:5678
VUE_APP_WS_HOST=ws://内网ip:5678
VUE_APP_USER=18575670125
VUE_APP_PASS=12345678
VUE_APP_ADMIN_USER=admin
VUE_APP_ADMIN_PASS=admin123
VUE_APP_KEY_PREFIX=ChatPLUS_DEV_
VUE_APP_TITLE="ChatGPT-PLUS V3"

.env.production:
保持默认

**Comment by fangzheng123** [comment]
> 使用公网 IP 访问，如果是通过容器部署的话，除了 nginx 的 server_name 需要配置公网成公网 IP，其他配置都设置成内网 IP 即可。另外，.env.production 配置保持默认即可，无需改动。

您好，目前还是无法使用公网IP访问，相关配置和docker截图已添加到评论中，您觉得可能是哪里的问题呢（8080端口已对外开放了）

**Comment by yangjian102621** [comment]
1. 请提供容器后端的报错日志。
2. 提供报错相关的截图，包括浏览器控制台网络请求面板的截图。

**Comment by fangzheng123** [comment]
> 1. 请提供容器后端的报错日志。
> 2. 提供报错相关的截图，包括浏览器控制台网络请求面板的截图。

chatgpt-plus-web容器日志如下：
![image](https://github.com/yangjian102621/chatgpt-plus/assets/11494089/825bc909-3eda-4152-a0a1-76e8cf52d1f2)


chatgpt-plus-api容器日志如下：
![image](https://github.com/yangjian102621/chatgpt-plus/assets/11494089/3b1606b3-992b-44dc-9711-bcde275af26e)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/11494089/26b35462-5a84-4c96-bd8d-77a11ccb4d73)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/11494089/902dbd84-49cf-4d62-8591-13fe9c0be108)

mysql容器日志：
![image](https://github.com/yangjian102621/chatgpt-plus/assets/11494089/4dcdb372-bf5a-443d-b1cc-1cf8bd14e703)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/11494089/79ec03fe-940d-4f79-aadb-a266a794969a)

浏览器日志：
<img width="1549" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/11494089/b41bcaf3-786b-49da-83f7-5246b360c78c">

感谢博主的指导！

**Comment by yangjian102621** [comment]
![image](https://github.com/yangjian102621/chatgpt-plus/assets/4746061/4ab38d60-4497-4d19-9ea2-ac7d236abbe9)
本地访问有结果说明服务启动没有问题，外网访问502，那说明你外网的 8080 端口并不是映射内网的 8080端口，你要看下你阿里云的网络安全策略配置的是否有问题。

**Comment by fangzheng123** [comment]
> ![image](https://user-images.githubusercontent.com/4746061/275363929-4ab38d60-4497-4d19-9ea2-ac7d236abbe9.png) 本地访问有结果说明服务启动没有问题，外网访问502，那说明你外网的 8080 端口并不是映射内网的 8080端口，你要看下你阿里云的网络安全策略配置的是否有问题。

我之前使用宝塔开放端口，阿里云后台未配置，配置完端口后可以访问了，多谢博主！
