### ISSUE TITLE
English Version

### ISSUE THREAD

**Issue by hany-girgis** [yangjian102621/chatgpt-plus#45]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

Do you Provide an English Version, Is it possible that I Can I translate the project?

### 示例 🌈

English Version 

### 动机 🔦

English Version

**Comment by yangjian102621** [comment]
Sorry, this project does not support multi-languages, and there is no plan to do it unless other developers to contribute.
