### ISSUE TITLE
建议增加填写OpenAI Key的接口代理地址功能

### ISSUE THREAD

**Issue by MoonWeSif** [yangjian102621/chatgpt-plus#46]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

添加OpenAI的APIkey时，可以自行指定填写接口地址（若不填写则为默认接口地址）

### 动机 🔦

相较于在服务器中使用代理，使用CF或者其他人提供的代理地址对于国内服务器来说更加简单易用，默认情况下可以为官方的接口地址。如果有需求则可以用户自己指定API接口的代理地址。
同时这样做还有一个好处就是目前许多商家提供中转API服务，都需要填写商家指定的接口地址，这些中转API服务提供了许多OpenAI模型可供选择（而且4.0API调用价格比官方低），这样可以节约成本。

**Comment by yangjian102621** [comment]
此功能在系统配置里面已经提供，自行修改对应的 API 地址即可。

<img width="819" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/4746061/04580006-b8dc-4a84-b8c7-19ae023dc7ce">
