### ISSUE TITLE
配置了七牛，过几个小时再上传就会提示expired token。

### ISSUE THREAD

**Issue by pw6666** [yangjian102621/chatgpt-plus#48]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

配置了**七牛云存储**。
如果是api服务**刚启动**，可以**正常上传头像**。
[![QQ截图20231109082100]()](https://github.com/yangjian102621/chatgpt-plus/assets/51316972/ee2940c9-ed3c-4db4-8e63-829db8bacb97)

**过几个小时**之后，再上传头像就会提示**expired token**！
[![QQ截图20231109081715]()](https://github.com/yangjian102621/chatgpt-plus/assets/51316972/930be508-5707-4f75-a879-1dc2b5c338a4)

重启服务，就又能正常几个小时。

### 重现步骤 🕹

如果选择**本地存储**，不存在这个问题。

### 你的应用配置信息

[![QQ截图20231109083536]()
](https://github.com/yangjian102621/chatgpt-plus/assets/51316972/a79c0542-07c4-46d1-a425-74d550711e96)

**Comment by yangjian102621** [comment]
这个 Bug 已经确认，是因为缓存了上传的 token，目前已经修复，每次上传重新生成 token，修复功能将在下个版本连同充值支付功能同步上线。
