### ISSUE TITLE
SD绘图额度Bug

### ISSUE THREAD

**Issue by wshze** [yangjian102621/chatgpt-plus#49]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

SD绘图每次提交一张额度就会减一，看上去没啥问题。实际刷新浏览器额度又回来了。

### 重现步骤 🕹

sd刷新浏览器或重新登录额度又回来了。

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
要绘图任务完成之后才会真正扣减次数的。如果任务失败扣减次数会回滚的。

**Comment by wshze** [comment]
![001](https://github.com/yangjian102621/chatgpt-plus/assets/42234694/2565f926-f9df-4039-8e1d-df9e8219de32)
![002](https://github.com/yangjian102621/chatgpt-plus/assets/42234694/52baf4a1-287a-466c-a405-97de0a1e81a9)
![003](https://github.com/yangjian102621/chatgpt-plus/assets/42234694/cd01bc7d-78f7-45cd-953e-8c1ca9dc2af5)
![004](https://github.com/yangjian102621/chatgpt-plus/assets/42234694/73eb6c4f-4278-48e0-94ca-ec8def3e15ba
任务成功了的。

**Comment by yangjian102621** [comment]
收到，已经修复，将在 v3.1.8 版本发布。
https://github.com/yangjian102621/chatgpt-plus/commit/baddabaa1624798ebd8a5f5d5e6b01c9008111d9

**Comment by wshze** [comment]
试了下v3.1.8版本这个好像还是没有减少，刷新浏览器额度又回来了。是不是没写数据库？
