### ISSUE TITLE
后台登录提示网络错误

### ISSUE THREAD

**Issue by alongLFB** [yangjian102621/chatgpt-plus#5]
<img width="642" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/17883682/1fb57190-0522-4510-8079-6fa821933489">

<img width="484" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/17883682/b6e26811-55b8-4528-bb79-6d4496b6de7b">

**Comment by yangjian102621** [comment]
这个通常是跨域问题导致的，检查一下  config.toml 的 ` Domain = ""` 配置和前端的 `VUE_APP_API_HOST` 配置的是不是同一个域名。

> <img alt="image" width="642" src="https://user-images.githubusercontent.com/17883682/242848150-1fb57190-0522-4510-8079-6fa821933489.png"> <img alt="image" width="484" src="https://user-images.githubusercontent.com/17883682/242848088-b6e26811-55b8-4528-bb79-6d4496b6de7b.png">
