### ISSUE TITLE
新建会话时，提示"请输入合法的手机号"

### ISSUE THREAD

**Issue by jy00566722** [yangjian102621/chatgpt-plus#51]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-4

### 操作系统

MacOS

## 新建会话时后，发出第一条问题时提示:"请输入合法的手机号"

![image](https://github.com/yangjian102621/chatgpt-plus/assets/590583/2fe190c9-cf8b-4931-ad44-e5100c5fa7c8)

### 重现步骤 🕹

有时候出现，有时候不出现。

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by wshze** [comment]
我以前有出现过一次，当时是客户端（浏览器用户）到服务器网络不好的情况下出现的。不知道是不是这个原因

**Comment by yangjian102621** [comment]
这个是登录组件在销毁的时候没有卸载事件导致的，已修复。
