### ISSUE TITLE
Is it possible to use caddy, instead of Nginx

### ISSUE THREAD

**Issue by ikexue** [yangjian102621/chatgpt-plus#54]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

Is it possible to use caddy, instead of Nginx, because caddy can automatically generate https and it is easier to use the reverse proxy mode

### 示例 🌈

能否使用caddy，替换掉Nginx，因为caddy能够自动生成https，而且更容易使用反代模式

### 动机 🔦

如果使用caddy服务器，就不用单独申请域名的https

**Comment by yangjian102621** [comment]
您可以贡献一套 caddy 的解决方案，与 NGINX 并行为可选方案。
