### ISSUE TITLE
sd的prompt是否可以支持翻译

### ISSUE THREAD

**Issue by waynesun01** [yangjian102621/chatgpt-plus#56]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

sd如果输入中文，生成效果很差，是否可以支持将prompt翻译后再生成呢
加个翻译接口

### 示例 🌈

加个翻译接口

### 动机 🔦

加个翻译接口

**Comment by yangjian102621** [comment]
@waynesun01 这个会考虑加入的，下个版本就可以加入该功能。
