### ISSUE TITLE
接口是否考虑集中管理

### ISSUE THREAD

**Issue by ken678** [yangjian102621/chatgpt-plus#57]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

对接其他语言接口，接口分散在不同vue文件，后端接口取名和你的不一致的话 修改起来较为麻烦

### 示例 🌈

无

### 动机 🔦

无

**Comment by yangjian102621** [comment]
前端我不熟悉，需要有前端高手牵头做这个事情。
