### ISSUE TITLE
PC端对话在刷新后异常

### ISSUE THREAD

**Issue by jy00566722** [yangjian102621/chatgpt-plus#59]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-4

### 操作系统

MacOS

### Bug 描述 📝

这个问题我发现很久了，但一直没重视，今天特别明显。我新启了一个对话，回答完了，一共4条信息，都没有问题的。过一会，在一次自动刷新后，后面两条信息在对话中不见了。我马上去数据库中看，数据库中还有，但是chat_id变了。不是和前两句一样的。
<img width="1655" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/590583/a280b9bd-b4a3-4e57-b419-5ca6318a2d17">
<img width="989" alt="image" src="https://github.com/yangjian102621/chatgpt-plus/assets/590583/5c460271-b381-428e-a011-4fe769ca9c14">

### 重现步骤 🕹

就我现在的环境，很容易重现。在上面那个对话后，我后面的几个对话，都有一样的情况。有没有可能是因为对话的标题太像导致，因为我是直接复制之前的问题，新启对话，这样会导致标题一样(在对话列表中前几个字符就是一样的).

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by jy00566722** [comment]
纯文本也是一样。


ShenKeeeew ***@***.***>于2023年12月2日 周六10:43写道：

**Comment by yangjian102621** [comment]
@jy00566722 收到，我这边还是没法重现，估计是中途切换了模型或者角色导致的。我改了下代码，在切换模型或者角色的时候自动新建会话，结束旧的对话。
