### ISSUE TITLE
admin 默认的账号密码是什么

### ISSUE THREAD

**Issue by hcj5206** [yangjian102621/chatgpt-plus#60]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

成功部署后，不知道后台的账号和密码

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by doresu** [comment]
admin123
