### ISSUE TITLE
验证码无法保存

### ISSUE THREAD

**Issue by jty1379** [yangjian102621/chatgpt-plus#61]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

注册的时候可以向新手机号发送验证码，但提示无法保存，然后无法注册（验证码错误）

### 重现步骤 🕹

正常注册

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
这个是线上演示站的 redis 服务崩了，目前已经恢复。
