### ISSUE TITLE
请问最低需要什么配置

### ISSUE THREAD

**Issue by CatAnd-Dog** [yangjian102621/chatgpt-plus#63]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

请问最低需要什么配置

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
1核1G
