### ISSUE TITLE
已按安装文档配置了config.toml和上传了支付宝证书，但是chatgpt-plus-api容器启动不了

### ISSUE THREAD

**Issue by hntjb** [yangjian102621/chatgpt-plus#64]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

![image](https://github.com/yangjian102621/chatgpt-plus/assets/89767313/30c5671c-7fc3-4f93-bd5e-8fdf21e14261)
![image](https://github.com/yangjian102621/chatgpt-plus/assets/89767313/25991191-c5b5-4418-81b0-4ef1d422d0c7)
已按安装文档配置了config.toml和上传了支付宝证书，但是chatgpt-plus-api容器启动不了，麻烦大佬看看我这是哪里出错了。

### 你的应用配置信息

![image](https://github.com/yangjian102621/chatgpt-plus/assets/89767313/44580e1a-b2ed-40e1-8fd6-c35e0b710f18)

**Comment by yangjian102621** [comment]
你要把这个目录挂载到容器，不然读取不到的 。

**Comment by wshze** [comment]
大佬。虎皮椒的支付没看到配置地方。是还没开发完吗

**Comment by hntjb** [comment]
> 你要把这个目录挂载到容器，不然读取不到的 。

那需要把这个目录挂载到容器的哪个目录下，谢谢。

**Comment by yangjian102621** [comment]
> 大佬。虎皮椒的支付没看到配置地方。是还没开发完吗

@wshze 已经上线了。演示站能够体验的。

**Comment by wshze** [comment]
@yangjian102621 
扫描充值页面生成的二维码发现链接是这样的：
:///api/payment/doPay?order_no=202312227143794952068136960&pay_way=hupi

我的后台配置如下：
[HuPiPayConfig]
  Enabled = true
  Name = "wechat"
  AppId = "2011111111"
  AppSecret = "111111asdfed"
  NotifyURL = "http://10.240.11.25:5678/api/payment/hupipay/notify"
  PayURL = ""

**Comment by yangjian102621** [comment]
> @yangjian102621 扫描充值页面生成的二维码发现链接是这样的： :///api/payment/doPay?order_no=202312227143794952068136960&pay_way=hupi
> 
> 我的后台配置如下： [HuPiPayConfig] Enabled = true Name = "wechat" AppId = "2011111111" AppSecret = "111111asdfed" NotifyURL = "http://10.240.11.25:5678/api/payment/hupipay/notify" PayURL = ""

为什么 PayURL 这个配置你留空呢？

**Comment by wshze** [comment]
[HuPiPayConfig]
  Enabled = true
  Name = "wechat"
  AppId = "201111155"
  AppSecret = "00b546260ad"
  NotifyURL = "http://10.240.11.25:5678/api/payment/hupipay/notify"
  PayURL = "10.240.11.25:5678"
  这样配置了还是不行。是我配置有问题吗？
![556677](https://github.com/yangjian102621/chatgpt-plus/assets/42234694/4c1393ac-9947-4eb1-b66d-8da378eaa27e)

**Comment by wshze** [comment]
打扰了。已解决
