### ISSUE TITLE
Sd.Pool.go初始化时Config覆盖问题

### ISSUE THREAD

**Issue by babyrjw** [yangjian102621/chatgpt-plus#65]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

pool.go 第22行：
`for k, config := range appConfig.MjConfigs `
pool.go 第27行：
`client := NewClient(&config, appConfig.ProxyURL)`
这里如果MjConfigs有多个，循环时config变量会不断被覆盖，第27行使用指针初始化，所有的client里的config都是最后一个MjConfig了，建议修改：
`client := NewClient(&appConfig.MjConfigs[k], appConfig.ProxyURL)`

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
@babyrjw 收到，目前已经改成使用实例而非指针模式了。代码稍后推送。
