### ISSUE TITLE
 golang.org/x/net@v0.10.0: missing go.sum entry; to add it:

### ISSUE THREAD

**Issue by geekyouth** [yangjian102621/chatgpt-plus#67]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

 golang.org/x/net@v0.10.0: missing go.sum entry; to add it:

![image](https://github.com/yangjian102621/chatgpt-plus/assets/12899262/e1f131b4-cc9e-4da9-b653-1c9d225a216d)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by babyrjw** [comment]
先要下载go module再编译呀

**Comment by yangjian102621** [comment]
先把依赖下载好，build 脚本也不是这样用的，要传入版本参数和架构参数
