### ISSUE TITLE
删除最后一个绘图任务后，界面不更行

### ISSUE THREAD

**Issue by babyrjw** [yangjian102621/chatgpt-plus#68]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

当成功删除最后一个绘图任务，界面不会更行
`const list = res.data
      let changed = false
      for (let i = 0; i < list.length; i++) {
        if (list[i]["img_url"] !== finishedJobs.value[i]["img_url"]) {
          changed = true
          break
        }
      }
      if (changed) {
        finishedJobs.value = list
      }`
当res.data为[]时，changed 为false

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
收到反馈，此问题已修复，目前还没有发布版本，如果需尝鲜请更新 main 分支代码编译。
