### ISSUE TITLE
Azure request fail

### ISSUE THREAD

**Issue by JingHong0202** [yangjian102621/chatgpt-plus#69]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-4

### 操作系统

Linux

### Bug 描述 📝

当把Azure api query 参数 api-version 值改成的非2023-05-15时，前端会出现异常如下图：
![image](https://github.com/yangjian102621/chatgpt-plus/assets/42438909/05aca44f-f10a-4aee-8640-19f47919fbaf)

docker api日志：
![image](https://github.com/yangjian102621/chatgpt-plus/assets/42438909/26a337ae-59b4-449f-8933-c36c40a330e3)

**Comment by yangjian102621** [comment]
Azure貌似 API 接口更新了，但是本人没有测试 KEY，所以一直没法测试，需要你自己调试。
