### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by destiny1123** [yangjian102621/chatgpt-plus#73]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Linux

### Bug 描述 📝

使用MJ绘画的时候，有时候能成功，有时候直接抛出异常，提示
panic: runtime error: invalid memory address or nil pointer dereference
文件位置是在chatgpt-plus-main/api/service/mj/bot.go:121
以下是完整报错信息
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1146d04]

goroutine 103 [running]:
chatplus/service/mj.(*Bot).messageUpdate(0xc0000102e8, 0xc000342380, 0xc0004bfb60)
	D:/chatgpt-plus-main (1)/chatgpt-plus-main/api/service/mj/bot.go:121 +0x104
github.com/bwmarrin/discordgo.messageUpdateEventHandler.Handle(0xc000508fd0?, 0x6d644a?, {0x13fedc0?, 0xc0004bfb60?})
	C:/Users/Administrator/sdk/go1.20.4/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/eventhandlers.go:873 +0x38
created by github.com/bwmarrin/discordgo.(*Session).handle
	C:/Users/Administrator/sdk/go1.20.4/pkg/mod/github.com/bwmarrin/discordgo@v0.27.1/event.go:171 +0x16a

### 重现步骤 🕹

使用的是docker部署的，使用的是有时候会报错，进度到93就抛出异常，然后这条任务就不会再执行了。有时候生成MJ图片又没有问题，出错概率挺频繁的。

### 你的应用配置信息

配置文件基本没变过

**Comment by yangjian102621** [comment]
具体使用的是哪个版本的代码？或者 commitID  是多少？

**Comment by destiny1123** [comment]
> 具体使用的是哪个版本的代码？或者 commitID 是多少？

使用的是3.2.0的版本

**Comment by yangjian102621** [comment]
感谢反馈，这个问题在新版v3.2.2 已经修复，请更新版本试下。

**Comment by destiny1123** [comment]
> 感谢反馈，这个问题在新版v3.2.2 已经修复，请更新版本试下。

使用最新版提示“MidJourney 池子中没有没有可用的服务！”，请问是什么原因会导致这个问题

**Comment by yangjian102621** [comment]
配置选项改了，支持池子。你看下最新的配置文档MJ选项

**Comment by destiny1123** [comment]
> 配置选项改了，支持池子。你看下最新的配置文档MJ选项
程序运行以后在执行MJ机器人的时候报错：
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x224862f]

goroutine 105 [running]:
chatplus/service/mj.(*Bot).messageUpdate(0xc000114280, 0xc000424380, 0xc000427650)
        D:/chatgpt-plus-main (1)/chatgpt-plus-main/api/service/mj/bot.go:139 +0x16f
github.com/bg5t/mydiscordgo.messageUpdateEventHandler.Handle(0xc000426b40, 0xc000424380, {0x2582160, 0xc000427650})
        C:/Users/Administrator/sdk/go1.20.4/pkg/mod/github.com/bg5t/mydiscordgo@v0.28.1/eventhandlers.go:873 +0xa3
created by github.com/bg5t/mydiscordgo.(*Session).handle
        C:/Users/Administrator/sdk/go1.20.4/pkg/mod/github.com/bg5t/mydiscordgo@v0.28.1/event.go:171 +0x245
        
 // code \api\service\mj\bot.go
func (b *Bot) messageUpdate(s *discordgo.Session, m *discordgo.MessageUpdate) {
	// ignore messages for other channels
	if m.GuildID != b.config.GuildId || m.ChannelID != b.config.ChanelId {
		return
	}
	// ignore messages for self
	if m.Author.ID == s.State.User.ID {
		return
	}
执行第三遍的时候，m.Author等于nil，前两遍都有值

配置文件如下:
[[MjConfigs]]
  Enabled = true
  UserToken = "xxxxxxxxxxxxxxxx"
  BotToken = "xxxxxxxxxxxxxxx"
  GuildId = "xxxxxxxxxxxxxxxxxx"
  ChanelId = "xxxxxxxxxxxxxxxxx"
  UseCDN = false
  DiscordAPI = ""
  DiscordCDN = ""
  DiscordGateway = ""
  
  请问是下面这几个参数没有配置的问题吗？要配什么？
  UseCDN = false
  DiscordAPI = ""
  DiscordCDN = ""
  DiscordGateway = ""

**Comment by destiny1123** [comment]
> m.GuildID ！= b.config.GuildId

我尝试着加一个判断，发现他可以正常工作了，不知道是不是这样操作的。
if m.Author == nil || m.Author.ID == s.State.User.ID {
return
}

**Comment by yangjian102621** [comment]
这样操作是可以的。不过通常 m.Author 不会是 nil 的。估计是 API 有更新。
