### ISSUE TITLE
mj绘图 放大图片时错误

### ISSUE THREAD

**Issue by gianni2009** [yangjian102621/chatgpt-plus#91]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到跟我问题相关的问题。

### GPT-3 or GPT-4

GPT-3.5

### 操作系统

Windows

### Bug 描述 📝

mj画图输出4个图，选择其中一个重绘的时候，返回错误
![1](https://github.com/yangjian102621/chatgpt-plus/assets/153248944/74985cac-21e3-4d71-8c1b-f94ea95c6331)
![2](https://github.com/yangjian102621/chatgpt-plus/assets/153248944/e1a2f43e-6fbd-48b8-90b9-2ecd2332b0d9)

### 你的应用配置信息

```toml
把你的配置信息粘贴到这里
```

**Comment by yangjian102621** [comment]
感谢反馈，当前 Bug 已经修复。将在 v3.2.4 版本上线。
