### ISSUE TITLE
建议添加文件分析功能

### ISSUE THREAD

**Issue by gianni2009** [yangjian102621/chatgpt-plus#93]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

希望添加文件上传分析功能，
1、有的大模型不支持文件分析，需要先区分识别一下
2、如果支持文件分析，就显示文件上传按钮，否则不显示
3、如果能返回文件，或文件下载链接（ppt pdf word wps 等）
![微信图片_20240104094453](https://github.com/yangjian102621/chatgpt-plus/assets/153248944/f77b4b26-de36-4e82-b37b-6f35d6ee6510)

**Comment by yangjian102621** [comment]
目前在 gpt-4-all 模型中已经支持文档分析了。
