### ISSUE TITLE
关于MJ的代理服务对接形式是否支持

### ISSUE THREAD

**Issue by sunsky89757** [yangjian102621/chatgpt-plus#99]
### ⚠️  确认 issue 是否已存在 ⚠️

- [X] 我已经搜索了现有的问题，没有找到相关 issue。

### 功能描述 📝

https://github.com/novicezk/midjourney-proxy
请问是否支持这种形式的MJ对接呢?

**Comment by yangjian102621** [comment]
不支持，MJ 机器人项目内置集成了，不需要引入其他中间件，这样部署的时候会麻烦一些，对小白不友好，如果你资深用户，建议 fork 一份改造一下。

**Comment by yangjian102621** [comment]
v3.2.5 版本之后已经支持 MJ-Plus API 了
